name: kmdb
description:
  A local-first document database for Dart/Flutter with multi-device sync.
version: 1.0.0
repository: https://github.com/aurochs-kmesh/kmdb
publish_to: none

environment:
  sdk: ^3.10.8

resolution: workspace

dependencies:
  cbor: ^6.5.1
  kmdb_zstd:
  meta: any
  uuid: ^4.5.3
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.13.1
  mockito: ^5.6.4
