name: kmdb
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/aurochs-kmesh/kmdb
publish_to: none

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  archive: ^4.0.9
  cbor: ^6.5.1
  meta: any
  uuid: ^4.5.3
  web: ^1.0.0
  es_compression: ^2.0.15
  # path: ^1.9.0

dev_dependencies:
  build_runner: ^2.13.1
  lints: ^6.0.0
  mockito: ^5.6.4
  test: ^1.25.6
