name: kmdb_harness
description: Developer test harness for KMDB's multi-device sync protocol.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  kmdb:
  args: ^2.6.0
  uuid:

dev_dependencies:
  lints: ^6.1.0
  path: ^1.9.0
  test: ^1.30.0
