/*
Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names

import '../registry_base.dart';
import 'package:meta/meta.dart';

@internal
final Map<String, RegistryEntry> mimeinfoDbAudio = {
  "audio/x-amzxml": const RegistryEntry(
    mediaType: 'audio/x-amzxml',
    comments: ['AmazonMP3 download file'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.amz', weight: 50, caseSensitive: false)],
  ),
  "audio/x-gsm": const RegistryEntry(
    mediaType: 'audio/x-gsm',
    comments: ['GSM 06.10 audio'],
    acronym: 'GSM',
    expandedAcronym: 'Global System for Mobile communications',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gsm', weight: 50, caseSensitive: false)],
  ),
  "audio/x-iriver-pla": const RegistryEntry(
    mediaType: 'audio/x-iriver-pla',
    comments: ['iRiver playlist'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pla', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'iriver UMS PLA',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-matroska": const RegistryEntry(
    mediaType: 'audio/x-matroska',
    comments: ['Matroska audio'],
    subclassOf: ['application/x-matroska'],
    alias: [],
    globs: [Glob(pattern: '*.mka', weight: 50, caseSensitive: false)],
  ),
  "audio/webm": const RegistryEntry(
    mediaType: 'audio/webm',
    comments: ['WebM audio'],
    subclassOf: ['video/webm'],
    alias: [],
  ),
  "audio/annodex": const RegistryEntry(
    mediaType: 'audio/annodex',
    comments: ['Annodex audio'],
    subclassOf: ['application/annodex'],
    alias: ['audio/x-annodex'],
    globs: [Glob(pattern: '*.axa', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'OggS',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: 'fishead\x00',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.string,
                    offset: '56:512',
                    value: 'CMML\x00\x00\x00\x00',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/ogg": const RegistryEntry(
    mediaType: 'audio/ogg',
    comments: ['Ogg audio'],
    subclassOf: ['application/ogg'],
    alias: ['audio/x-ogg'],
    globs: [
      Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
      Glob(pattern: '*.opus', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'OggS', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-vorbis+ogg": const RegistryEntry(
    mediaType: 'audio/x-vorbis+ogg',
    comments: ['Ogg Vorbis audio'],
    subclassOf: ['audio/ogg'],
    alias: ['audio/vorbis', 'audio/x-vorbis'],
    globs: [
      Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'OggS',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: '\x01vorbis',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-flac+ogg": const RegistryEntry(
    mediaType: 'audio/x-flac+ogg',
    comments: ['Ogg FLAC audio'],
    subclassOf: ['audio/ogg'],
    alias: ['audio/x-oggflac'],
    globs: [
      Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'OggS',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: 'fLaC',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'OggS',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: '\x7fFLAC',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-opus+ogg": const RegistryEntry(
    mediaType: 'audio/x-opus+ogg',
    comments: ['Opus audio'],
    subclassOf: ['audio/ogg'],
    alias: [],
    globs: [Glob(pattern: '*.opus', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'OggS',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: 'OpusHead',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-speex+ogg": const RegistryEntry(
    mediaType: 'audio/x-speex+ogg',
    comments: ['Ogg Speex audio'],
    subclassOf: ['audio/ogg'],
    alias: [],
    globs: [
      Glob(pattern: '*.oga', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ogg', weight: 50, caseSensitive: false),
      Glob(pattern: '*.spx', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'OggS',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: 'Speex  ',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-speex": const RegistryEntry(
    mediaType: 'audio/x-speex',
    comments: ['Speex audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.spx', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'Speex',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-xmf": const RegistryEntry(
    mediaType: 'audio/x-xmf',
    comments: ['XMF audio'],
    acronym: 'XMF',
    expandedAcronym: 'eXtensible Music Format',
    subclassOf: [],
    alias: ['audio/xmf'],
    globs: [Glob(pattern: '*.xmf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'XMF_', mask: null),
        ],
      ),
    ],
  ),
  "audio/mobile-xmf": const RegistryEntry(
    mediaType: 'audio/mobile-xmf',
    comments: ['Mobile XMF audio'],
    acronym: 'XMF',
    expandedAcronym: 'eXtensible Music Format',
    subclassOf: [],
    alias: ['audio/vnd.nokia.mobile-xmf'],
    globs: [Glob(pattern: '*.mxmf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'XMF_2.00\x00\x00\x00\x02',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/ac3": const RegistryEntry(
    mediaType: 'audio/ac3',
    comments: ['Dolby Digital audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ac3', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0x0b77',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/vnd.dts": const RegistryEntry(
    mediaType: 'audio/vnd.dts',
    comments: ['DTS audio'],
    acronym: 'DTS',
    expandedAcronym: 'Digital Theater Systems',
    subclassOf: [],
    alias: ['audio/x-dts'],
    globs: [Glob(pattern: '*.dts', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x7FFE8001',
            mask: null,
          ),
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0xFE7F0180',
            mask: null,
          ),
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x1FFFE800',
            mask: null,
          ),
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0xFF1F00E8',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/vnd.dts.hd": const RegistryEntry(
    mediaType: 'audio/vnd.dts.hd',
    comments: ['DTS-HD audio'],
    acronym: 'DTS-HD',
    expandedAcronym: 'Digital Theater Systems High Definition',
    subclassOf: ['audio/vnd.dts'],
    alias: ['audio/x-dtshd'],
    globs: [Glob(pattern: '*.dtshd', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 60,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x7FFE8001',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big32,
                offset: '4:18725',
                value: '0x64582025',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/AMR": const RegistryEntry(
    mediaType: 'audio/AMR',
    comments: ['AMR audio'],
    acronym: 'AMR',
    expandedAcronym: 'Adaptive Multi-Rate',
    subclassOf: [],
    alias: ['audio/amr-encrypted'],
    globs: [Glob(pattern: '*.amr', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '#!AMR\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '#!AMR_MC1.0\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/AMR-WB": const RegistryEntry(
    mediaType: 'audio/AMR-WB',
    comments: ['AMR-WB audio'],
    acronym: 'AMR-WB',
    expandedAcronym: 'Adaptive Multi-Rate Wideband',
    subclassOf: [],
    alias: ['audio/amr-wb-encrypted'],
    globs: [Glob(pattern: '*.awb', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '#!AMR-WB\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '#!AMR-WB_MC1.0\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/basic": const RegistryEntry(
    mediaType: 'audio/basic',
    comments: ['ULAW (Sun) audio'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.au', weight: 50, caseSensitive: false),
      Glob(pattern: '*.snd', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 40,
        matches: [
          Match(type: MatchType.string, offset: '0', value: '.snd', mask: null),
        ],
      ),
    ],
  ),
  "audio/prs.sid": const RegistryEntry(
    mediaType: 'audio/prs.sid',
    comments: ['Commodore 64 audio'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.sid', weight: 50, caseSensitive: false),
      Glob(pattern: '*.psid', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'PSID', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-adpcm": const RegistryEntry(
    mediaType: 'audio/x-adpcm',
    comments: ['PCM audio'],
    acronym: 'PCM',
    expandedAcronym: 'Pulse-code Modulation',
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '.snd',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big32,
                offset: '12',
                value: '23',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x0064732E',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '1',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '2',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '3',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '4',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '5',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '6',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '7',
                mask: null,
              ),
              Match(
                type: MatchType.little32,
                offset: '12',
                value: '23',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-aifc": const RegistryEntry(
    mediaType: 'audio/x-aifc',
    comments: ['AIFC audio'],
    acronym: 'AIFC',
    expandedAcronym: 'Audio Interchange File format Compressed',
    subclassOf: ['application/x-iff'],
    alias: ['audio/x-aiffc'],
    globs: [
      Glob(pattern: '*.aifc', weight: 50, caseSensitive: false),
      Glob(pattern: '*.aiffc', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '8', value: 'AIFC', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-aiff": const RegistryEntry(
    mediaType: 'audio/x-aiff',
    comments: ['AIFF/Amiga/Mac audio'],
    acronym: 'AIFF',
    expandedAcronym: 'Audio Interchange File Format',
    subclassOf: ['application/x-iff'],
    alias: [],
    globs: [
      Glob(pattern: '*.aiff', weight: 50, caseSensitive: false),
      Glob(pattern: '*.aif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '8', value: 'AIFF', mask: null),
          Match(type: MatchType.string, offset: '8', value: '8SVX', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-ape": const RegistryEntry(
    mediaType: 'audio/x-ape',
    comments: ['Monkey\'s audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ape', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'MAC ', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-pn-audibleaudio": const RegistryEntry(
    mediaType: 'audio/x-pn-audibleaudio',
    comments: ['Audible.Com audio'],
    subclassOf: [],
    alias: ['audio/vnd.audible'],
    globs: [Glob(pattern: '*.aa', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '4',
            value: '1469084982',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/vnd.audible.aax": const RegistryEntry(
    mediaType: 'audio/vnd.audible.aax',
    comments: ['Audible Enhanced audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.aax', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypaax ',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/vnd.audible.aaxc": const RegistryEntry(
    mediaType: 'audio/vnd.audible.aaxc',
    comments: ['Audible Enhanced audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.aaxc', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypaaxc',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-dff": const RegistryEntry(
    mediaType: 'audio/x-dff',
    comments: ['DSDIFF audio'],
    acronym: 'DSDIFF',
    expandedAcronym: 'Direct Stream Digital Interchange File Format',
    subclassOf: [],
    alias: ['audio/dff'],
    globs: [Glob(pattern: '*.dff', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FRM8',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '12',
                value: 'DSD ',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-dsf": const RegistryEntry(
    mediaType: 'audio/x-dsf',
    comments: ['DSF audio'],
    acronym: 'DSF',
    expandedAcronym: 'Direct stream digital Stream File',
    subclassOf: [],
    alias: ['audio/dsf', 'audio/x-dsd', 'audio/dsd'],
    globs: [Glob(pattern: '*.dsf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'DSD ',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '28',
                value: 'fmt ',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.string,
                    offset: '80',
                    value: 'data',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "audio/x-it": const RegistryEntry(
    mediaType: 'audio/x-it',
    comments: ['Impulse Tracker audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.it', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'IMPM', mask: null),
        ],
      ),
    ],
  ),
  "audio/flac": const RegistryEntry(
    mediaType: 'audio/flac',
    comments: ['FLAC audio'],
    acronym: 'FLAC',
    expandedAcronym: 'Free Lossless Audio Codec',
    subclassOf: [],
    alias: ['audio/x-flac'],
    globs: [Glob(pattern: '*.flac', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'fLaC', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-tak": const RegistryEntry(
    mediaType: 'audio/x-tak',
    comments: ['TAK audio'],
    acronym: 'TAK',
    expandedAcronym: 'Tom\'s lossless Audio Kompressor',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.tak', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'tBaK', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-wavpack": const RegistryEntry(
    mediaType: 'audio/x-wavpack',
    comments: ['WavPack audio'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.wv', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wvp', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'wvpk', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-wavpack-correction": const RegistryEntry(
    mediaType: 'audio/x-wavpack-correction',
    comments: ['WavPack audio correction file'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.wvc', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'wvpk', mask: null),
        ],
      ),
    ],
  ),
  "audio/midi": const RegistryEntry(
    mediaType: 'audio/midi',
    comments: ['MIDI audio'],
    acronym: 'MIDI',
    expandedAcronym: 'Musical Instrument Digital Interface',
    subclassOf: [],
    alias: ['audio/x-midi'],
    globs: [
      Glob(pattern: '*.mid', weight: 50, caseSensitive: false),
      Glob(pattern: '*.midi', weight: 50, caseSensitive: false),
      Glob(pattern: '*.kar', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'MThd', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-mo3": const RegistryEntry(
    mediaType: 'audio/x-mo3',
    comments: ['Compressed Tracker audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.mo3', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'MO3', mask: null),
        ],
      ),
    ],
  ),
  "audio/aac": const RegistryEntry(
    mediaType: 'audio/aac',
    comments: ['AAC audio'],
    acronym: 'AAC',
    expandedAcronym: 'Advanced Audio Coding',
    subclassOf: [],
    alias: ['audio/x-aac'],
    globs: [
      Glob(pattern: '*.aac', weight: 50, caseSensitive: false),
      Glob(pattern: '*.adts', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ass', weight: 10, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'ADIF', mask: null),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xFFF0',
            mask: '0xFFF6',
          ),
        ],
      ),
    ],
  ),
  "audio/usac": const RegistryEntry(
    mediaType: 'audio/usac',
    comments: ['USAC audio'],
    acronym: 'USAC',
    expandedAcronym: 'Unified Speech and Audio Coding',
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.loas', weight: 50, caseSensitive: false),
      Glob(pattern: '*.xhe', weight: 50, caseSensitive: false),
    ],
  ),
  "audio/mp4": const RegistryEntry(
    mediaType: 'audio/mp4',
    comments: ['MPEG-4 audio'],
    subclassOf: [],
    alias: ['audio/x-m4a', 'audio/m4a'],
    globs: [
      Glob(pattern: '*.m4a', weight: 50, caseSensitive: false),
      Glob(pattern: '*.f4a', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypM4A',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-m4r": const RegistryEntry(
    mediaType: 'audio/x-m4r',
    comments: ['MPEG-4 ringtone'],
    subclassOf: ['video/mp4'],
    alias: [],
    globs: [Glob(pattern: '*.m4r', weight: 50, caseSensitive: false)],
  ),
  "audio/x-m4b": const RegistryEntry(
    mediaType: 'audio/x-m4b',
    comments: ['MPEG-4 audio book'],
    subclassOf: ['audio/mp4'],
    alias: [],
    globs: [
      Glob(pattern: '*.m4b', weight: 50, caseSensitive: false),
      Glob(pattern: '*.f4b', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypM4B',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-mod": const RegistryEntry(
    mediaType: 'audio/x-mod',
    comments: ['Amiga SoundTracker audio'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.mod', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ult', weight: 50, caseSensitive: false),
      Glob(pattern: '*.uni', weight: 50, caseSensitive: false),
      Glob(pattern: '*.m15', weight: 50, caseSensitive: false),
      Glob(pattern: '*.mtm', weight: 50, caseSensitive: false),
      Glob(pattern: '*.669', weight: 50, caseSensitive: false),
      Glob(pattern: '*.med', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 40,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'MTM', mask: null),
          Match(type: MatchType.string, offset: '0', value: 'MMD0', mask: null),
          Match(type: MatchType.string, offset: '0', value: 'MMD1', mask: null),
          Match(
            type: MatchType.byte,
            offset: '112',
            value: '0x0',
            mask: '0x80',
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '0',
                value: 'if',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.byte,
                    offset: '368',
                    value: '0x0',
                    mask: '0xe0',
                    subMatches: [
                      Match(
                        type: MatchType.byte,
                        offset: '110',
                        value: '0x0',
                        mask: '0xc0',
                        subMatches: [
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x0',
                            mask: '0x80',
                          ),
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x80',
                            mask: null,
                          ),
                        ],
                      ),
                      Match(
                        type: MatchType.byte,
                        offset: '110',
                        value: '0x40',
                        mask: null,
                        subMatches: [
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x0',
                            mask: '0x80',
                          ),
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x80',
                            mask: null,
                          ),
                        ],
                      ),
                    ],
                  ),
                  Match(
                    type: MatchType.byte,
                    offset: '368',
                    value: '0x20',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.byte,
                        offset: '110',
                        value: '0x0',
                        mask: '0xc0',
                        subMatches: [
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x0',
                            mask: '0x80',
                          ),
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x80',
                            mask: null,
                          ),
                        ],
                      ),
                      Match(
                        type: MatchType.byte,
                        offset: '110',
                        value: '0x40',
                        mask: null,
                        subMatches: [
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x0',
                            mask: '0x80',
                          ),
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x80',
                            mask: null,
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              Match(
                type: MatchType.string,
                offset: '0',
                value: 'JN',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.byte,
                    offset: '368',
                    value: '0x0',
                    mask: '0xe0',
                    subMatches: [
                      Match(
                        type: MatchType.byte,
                        offset: '110',
                        value: '0x0',
                        mask: '0xc0',
                        subMatches: [
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x0',
                            mask: '0x80',
                          ),
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x80',
                            mask: null,
                          ),
                        ],
                      ),
                    ],
                  ),
                  Match(
                    type: MatchType.byte,
                    offset: '368',
                    value: '0x20',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.byte,
                        offset: '110',
                        value: '0x40',
                        mask: null,
                        subMatches: [
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x0',
                            mask: '0x80',
                          ),
                          Match(
                            type: MatchType.byte,
                            offset: '111',
                            value: '0x80',
                            mask: null,
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'MAS_UTrack_V00',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1080',
            value: 'M.K.',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1080',
            value: 'M!K!',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/mp2": const RegistryEntry(
    mediaType: 'audio/mp2',
    comments: ['MP2 audio'],
    subclassOf: [],
    alias: ['audio/x-mp2'],
    globs: [Glob(pattern: '*.mp2', weight: 50, caseSensitive: false)],
  ),
  "audio/mpeg": const RegistryEntry(
    mediaType: 'audio/mpeg',
    comments: ['MP3 audio'],
    subclassOf: [],
    alias: ['audio/x-mp3', 'audio/x-mpg', 'audio/x-mpeg', 'audio/mp3'],
    globs: [
      Glob(pattern: '*.mp3', weight: 50, caseSensitive: false),
      Glob(pattern: '*.mpga', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xfffa',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xfffb',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xfff3',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xfff2',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xffe3',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xffe2',
            mask: null,
          ),
          Match(type: MatchType.string, offset: '0', value: 'ID3', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-mpegurl": const RegistryEntry(
    mediaType: 'audio/x-mpegurl',
    comments: ['Media playlist'],
    subclassOf: ['text/plain'],
    alias: [
      'audio/mpegurl',
      'application/m3u',
      'audio/x-mp3-playlist',
      'audio/m3u',
      'audio/x-m3u',
    ],
    globs: [
      Glob(pattern: '*.m3u', weight: 50, caseSensitive: false),
      Glob(pattern: '*.m3u8', weight: 50, caseSensitive: false),
      Glob(pattern: '*.vlc', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '#EXTM3U',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-ms-asx": const RegistryEntry(
    mediaType: 'audio/x-ms-asx',
    comments: ['Microsoft ASX playlist'],
    subclassOf: [],
    alias: [
      'video/x-ms-wvx',
      'video/x-ms-wax',
      'video/x-ms-wmx',
      'application/x-ms-asx',
    ],
    globs: [
      Glob(pattern: '*.asx', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wax', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wvx', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wmx', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 51,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'ASF ', mask: null),
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '<ASX',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '<asx',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '<Asx',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-psf": const RegistryEntry(
    mediaType: 'audio/x-psf',
    comments: ['PSF audio'],
    acronym: 'PSF',
    expandedAcronym: 'Portable Sound Format',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.psf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'PSF', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-minipsf": const RegistryEntry(
    mediaType: 'audio/x-minipsf',
    comments: ['MiniPSF audio'],
    acronym: 'MiniPSF',
    expandedAcronym: 'Miniature Portable Sound Format',
    subclassOf: ['audio/x-psf'],
    alias: [],
    globs: [Glob(pattern: '*.minipsf', weight: 50, caseSensitive: false)],
  ),
  "audio/x-psflib": const RegistryEntry(
    mediaType: 'audio/x-psflib',
    comments: ['PSFlib audio library'],
    acronym: 'PSFlib',
    expandedAcronym: 'Portable Sound Format Library',
    subclassOf: ['audio/x-psf'],
    alias: [],
    globs: [Glob(pattern: '*.psflib', weight: 50, caseSensitive: false)],
  ),
  "audio/x-ms-wma": const RegistryEntry(
    mediaType: 'audio/x-ms-wma',
    comments: ['Windows Media audio'],
    subclassOf: ['application/vnd.ms-asf'],
    alias: ['audio/wma'],
    globs: [Glob(pattern: '*.wma', weight: 50, caseSensitive: false)],
  ),
  "audio/x-musepack": const RegistryEntry(
    mediaType: 'audio/x-musepack',
    comments: ['Musepack audio'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.mpc', weight: 50, caseSensitive: false),
      Glob(pattern: '*.mpp', weight: 50, caseSensitive: false),
      Glob(pattern: '*.mp+', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'MP+', mask: null),
          Match(type: MatchType.string, offset: '0', value: 'MPCK', mask: null),
        ],
      ),
    ],
  ),
  "audio/vnd.rn-realaudio": const RegistryEntry(
    mediaType: 'audio/vnd.rn-realaudio',
    comments: ['RealAudio document'],
    subclassOf: [],
    alias: ['audio/x-pn-realaudio', 'audio/vnd.m-realaudio'],
    globs: [
      Glob(pattern: '*.ra', weight: 50, caseSensitive: false),
      Glob(pattern: '*.rax', weight: 50, caseSensitive: false),
    ],
  ),
  "audio/x-riff": const RegistryEntry(
    mediaType: 'audio/x-riff',
    comments: ['RIFF audio'],
    subclassOf: [],
    alias: [],
  ),
  "audio/x-s3m": const RegistryEntry(
    mediaType: 'audio/x-s3m',
    comments: ['Scream Tracker 3 audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.s3m', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '44',
            value: 'SCRM',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-scpls": const RegistryEntry(
    mediaType: 'audio/x-scpls',
    comments: ['MP3 ShoutCast playlist'],
    subclassOf: [],
    alias: ['application/pls', 'audio/scpls'],
    globs: [Glob(pattern: '*.pls', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '[playlist]',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '[Playlist]',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '[PLAYLIST]',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-stm": const RegistryEntry(
    mediaType: 'audio/x-stm',
    comments: ['Scream Tracker audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.stm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '20',
            value: '!Scream!\x1a',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '20',
            value: '!SCREAM!\x1a',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '20',
            value: 'BMOD2STM\x1a',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-voc": const RegistryEntry(
    mediaType: 'audio/x-voc',
    comments: ['VOC audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.voc', weight: 50, caseSensitive: false)],
  ),
  "audio/vnd.wave": const RegistryEntry(
    mediaType: 'audio/vnd.wave',
    comments: ['WAV audio'],
    subclassOf: ['application/x-riff'],
    alias: ['audio/wav', 'audio/x-wav'],
    globs: [Glob(pattern: '*.wav', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '8', value: 'WAVE', mask: null),
          Match(type: MatchType.string, offset: '8', value: 'WAV ', mask: null),
        ],
      ),
    ],
  ),
  "audio/x-xi": const RegistryEntry(
    mediaType: 'audio/x-xi',
    comments: ['FastTracker II instrument'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xi', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'Extended Instrument:',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-xm": const RegistryEntry(
    mediaType: 'audio/x-xm',
    comments: ['FastTracker II audio'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'Extended Module:',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "audio/x-tta": const RegistryEntry(
    mediaType: 'audio/x-tta',
    comments: ['TrueAudio audio'],
    subclassOf: [],
    alias: ['audio/tta'],
    globs: [Glob(pattern: '*.tta', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'TTA1', mask: null),
        ],
      ),
    ],
  ),
};
