/*
Copyright 2026 The KMDB Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names

import '../registry_base.dart';
import 'package:meta/meta.dart';

@internal
final Map<String, RegistryEntry> mimeinfoDbImage = {
  "image/x-skencil": const RegistryEntry(
    mediaType: 'image/x-skencil',
    comments: ['Skencil document'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.sk', weight: 50, caseSensitive: false),
      Glob(pattern: '*.sk1', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '##Sketch',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/vnd.rn-realpix": const RegistryEntry(
    mediaType: 'image/vnd.rn-realpix',
    comments: ['RealPix document'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.rp', weight: 50, caseSensitive: false)],
  ),
  "image/bmp": const RegistryEntry(
    mediaType: 'image/bmp',
    comments: ['Windows BMP image'],
    subclassOf: [],
    alias: ['image/x-bmp', 'image/x-MS-bmp'],
    globs: [
      Glob(pattern: '*.bmp', weight: 50, caseSensitive: false),
      Glob(pattern: '*.dib', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'BMxxxx\x00\x00',
            mask: '0xffff00000000ffff',
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'BM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '14',
                value: '12',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '14',
                value: '64',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '14',
                value: '40',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/vnd.wap.wbmp": const RegistryEntry(
    mediaType: 'image/vnd.wap.wbmp',
    comments: ['WBMP image'],
    acronym: 'WBMP',
    expandedAcronym: 'WAP bitmap',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.wbmp', weight: 50, caseSensitive: false)],
  ),
  "image/cgm": const RegistryEntry(
    mediaType: 'image/cgm',
    comments: ['CGM image'],
    acronym: 'CGM',
    expandedAcronym: 'Computer Graphics Metafile',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.cgm', weight: 50, caseSensitive: false)],
  ),
  "image/g3fax": const RegistryEntry(
    mediaType: 'image/g3fax',
    comments: ['CCITT G3 fax image'],
    acronym: 'CCITT',
    expandedAcronym:
        'Comit\xe9 Consultatif International T\xe9l\xe9phonique et T\xe9l\xe9graphique',
    subclassOf: [],
    alias: ['image/fax-g3'],
    globs: [Glob(pattern: '*.g3', weight: 50, caseSensitive: false)],
  ),
  "image/gif": const RegistryEntry(
    mediaType: 'image/gif',
    comments: ['GIF image'],
    acronym: 'GIF',
    expandedAcronym: 'Graphics Interchange Format',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gif', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'GIF8', mask: null),
        ],
      ),
    ],
  ),
  "image/heif": const RegistryEntry(
    mediaType: 'image/heif',
    comments: ['HEIF image'],
    acronym: 'HEIF',
    expandedAcronym: 'High Efficiency Image File',
    subclassOf: [],
    alias: ['image/heic', 'image/heic-sequence', 'image/heif-sequence'],
    globs: [
      Glob(pattern: '*.heic', weight: 50, caseSensitive: false),
      Glob(pattern: '*.heif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.hif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 40,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypmif1',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypmsf1',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypheic',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypheix',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftyphevc',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftyphevx',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/ief": const RegistryEntry(
    mediaType: 'image/ief',
    comments: ['IEF image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ief', weight: 50, caseSensitive: false)],
  ),
  "image/jpeg": const RegistryEntry(
    mediaType: 'image/jpeg',
    comments: ['JPEG image'],
    acronym: 'JPEG',
    expandedAcronym: 'Joint Photographic Experts Group',
    subclassOf: [],
    alias: ['image/pjpeg'],
    globs: [
      Glob(pattern: '*.jpg', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpeg', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpe', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jfif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\xff\xd8\xff',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xffd8',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-jp2-codestream": const RegistryEntry(
    mediaType: 'image/x-jp2-codestream',
    comments: ['JPEG-2000 codestream'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.j2c', weight: 50, caseSensitive: false),
      Glob(pattern: '*.j2k', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpc', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xff4fff51',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/jp2": const RegistryEntry(
    mediaType: 'image/jp2',
    comments: ['JPEG-2000 JP2 image'],
    acronym: 'JP2',
    expandedAcronym: 'JPEG-2000',
    subclassOf: [],
    alias: ['image/jpeg2000', 'image/jpeg2000-image', 'image/x-jpeg2000-image'],
    globs: [
      Glob(pattern: '*.jp2', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpg2', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fjP  \r\n\x87\n        jp2 ',
            mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/jpx": const RegistryEntry(
    mediaType: 'image/jpx',
    comments: ['JPEG-2000 JPX image'],
    acronym: 'JPX',
    expandedAcronym: 'JPEG-2000 eXtended',
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.jpf', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpx', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fjP  \r\n\x87\n        jpx ',
            mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/jpm": const RegistryEntry(
    mediaType: 'image/jpm',
    comments: ['JPEG-2000 JPM image'],
    acronym: 'JPM',
    expandedAcronym: 'JPEG-2000 Mixed',
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.jpm', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpgm', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fjP  \r\n\x87\n        jpm ',
            mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/jxl": const RegistryEntry(
    mediaType: 'image/jxl',
    comments: ['JPEG XL image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.jxl', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\xff\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fJXL \r\n\x87\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/openraster": const RegistryEntry(
    mediaType: 'image/openraster',
    comments: ['OpenRaster image'],
    subclassOf: ['application/zip'],
    alias: [],
    globs: [Glob(pattern: '*.ora', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 70,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'PK\x03\x04',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '30',
                value: 'mimetype',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.string,
                    offset: '38',
                    value: 'image/openraster',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-dds": const RegistryEntry(
    mediaType: 'image/x-dds',
    comments: ['DirectDraw surface'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.dds', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'DDS', mask: null),
        ],
      ),
    ],
  ),
  "image/x-xcursor": const RegistryEntry(
    mediaType: 'image/x-xcursor',
    comments: ['X11 cursor'],
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'Xcur', mask: null),
        ],
      ),
    ],
  ),
  "image/x-exr": const RegistryEntry(
    mediaType: 'image/x-exr',
    comments: ['EXR image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.exr', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '20000630',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-pict": const RegistryEntry(
    mediaType: 'image/x-pict',
    comments: ['Macintosh Quickdraw/PICT drawing'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.pct', weight: 50, caseSensitive: false),
      Glob(pattern: '*.pict', weight: 50, caseSensitive: false),
      Glob(pattern: '*.pict1', weight: 50, caseSensitive: false),
      Glob(pattern: '*.pict2', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '10',
            value: '0x0011',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big16,
                offset: '12',
                value: '0x02FF',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big16,
                    offset: '14',
                    value: '0x0C00',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.big16,
                        offset: '16',
                        value: '0xFFFE',
                        mask: null,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '522',
            value: '0x0011',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big16,
                offset: '524',
                value: '0x02FF',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big16,
                    offset: '526',
                    value: '0x0C00',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.big16,
                        offset: '528',
                        value: '0xFFFE',
                        mask: null,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-dcraw": const RegistryEntry(
    mediaType: 'image/x-dcraw',
    comments: ['Digital raw image'],
    subclassOf: [],
    alias: [],
  ),
  "image/x-adobe-dng": const RegistryEntry(
    mediaType: 'image/x-adobe-dng',
    comments: ['Adobe DNG negative'],
    acronym: 'DNG',
    expandedAcronym: 'Digital Negative',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.dng', weight: 50, caseSensitive: false)],
  ),
  "image/x-canon-crw": const RegistryEntry(
    mediaType: 'image/x-canon-crw',
    comments: ['Canon CRW raw image'],
    acronym: 'CRW',
    expandedAcronym: 'Canon RaW',
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.crw', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'II\x1a\x00\x00\x00HEAPCCDR',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-canon-cr2": const RegistryEntry(
    mediaType: 'image/x-canon-cr2',
    comments: ['Canon CR2 raw image'],
    acronym: 'CR2',
    expandedAcronym: 'Canon Raw 2',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.cr2', weight: 50, caseSensitive: false)],
  ),
  "image/x-canon-cr3": const RegistryEntry(
    mediaType: 'image/x-canon-cr3',
    comments: ['Canon CR3 raw image'],
    acronym: 'CR3',
    expandedAcronym: 'Canon Raw 3',
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.cr3', weight: 50, caseSensitive: false)],
  ),
  "image/x-fuji-raf": const RegistryEntry(
    mediaType: 'image/x-fuji-raf',
    comments: ['Fuji RAF raw image'],
    acronym: 'RAF',
    expandedAcronym: 'RAw Format',
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.raf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FUJIFILMCCD-RAW ',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-kodak-dcr": const RegistryEntry(
    mediaType: 'image/x-kodak-dcr',
    comments: ['Kodak DCR raw image'],
    acronym: 'DCR',
    expandedAcronym: 'Digital Camera Raw',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.dcr', weight: 50, caseSensitive: false)],
  ),
  "image/x-kodak-k25": const RegistryEntry(
    mediaType: 'image/x-kodak-k25',
    comments: ['Kodak K25 raw image'],
    acronym: 'K25',
    expandedAcronym: 'Kodak DC25',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.k25', weight: 50, caseSensitive: false)],
  ),
  "image/x-kodak-kdc": const RegistryEntry(
    mediaType: 'image/x-kodak-kdc',
    comments: ['Kodak KDC raw image'],
    acronym: 'KDC',
    expandedAcronym: 'Kodak Digital Camera',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.kdc', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '242',
            value: 'EASTMAN KODAK COMPANY',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-minolta-mrw": const RegistryEntry(
    mediaType: 'image/x-minolta-mrw',
    comments: ['Minolta MRW raw image'],
    acronym: 'MRW',
    expandedAcronym: 'Minolta RaW',
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.mrw', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00MRM',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-nikon-nef": const RegistryEntry(
    mediaType: 'image/x-nikon-nef',
    comments: ['Nikon NEF raw image'],
    acronym: 'NEF',
    expandedAcronym: 'Nikon Electronic Format',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.nef', weight: 50, caseSensitive: false)],
  ),
  "image/x-nikon-nrw": const RegistryEntry(
    mediaType: 'image/x-nikon-nrw',
    comments: ['Nikon NRW raw image'],
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.nrw', weight: 50, caseSensitive: false)],
  ),
  "image/x-olympus-orf": const RegistryEntry(
    mediaType: 'image/x-olympus-orf',
    comments: ['Olympus ORF raw image'],
    acronym: 'ORF',
    expandedAcronym: 'Olympus Raw Format',
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.orf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'IIRO\b\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-panasonic-rw": const RegistryEntry(
    mediaType: 'image/x-panasonic-rw',
    comments: ['Panasonic raw image'],
    subclassOf: ['image/x-dcraw'],
    alias: ['image/x-panasonic-raw'],
    globs: [Glob(pattern: '*.raw', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'IIU\x00\b\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-panasonic-rw2": const RegistryEntry(
    mediaType: 'image/x-panasonic-rw2',
    comments: ['Panasonic raw image'],
    subclassOf: ['image/x-dcraw'],
    alias: ['image/x-panasonic-raw2'],
    globs: [Glob(pattern: '*.rw2', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'IIU\x00\x18\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-pentax-pef": const RegistryEntry(
    mediaType: 'image/x-pentax-pef',
    comments: ['Pentax PEF raw image'],
    acronym: 'PEF',
    expandedAcronym: 'Pentax Electronic Format',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.pef', weight: 50, caseSensitive: false)],
  ),
  "image/x-sigma-x3f": const RegistryEntry(
    mediaType: 'image/x-sigma-x3f',
    comments: ['Sigma X3F raw image'],
    acronym: 'X3F',
    expandedAcronym: 'X3 Foveon',
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.x3f', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FOVb',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little32,
                offset: '4',
                value: '0x00FF00FF',
                mask: '0xFF00FF00',
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-sony-srf": const RegistryEntry(
    mediaType: 'image/x-sony-srf',
    comments: ['Sony SRF raw image'],
    acronym: 'SRF',
    expandedAcronym: 'Sony Raw Format',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.srf', weight: 50, caseSensitive: false)],
  ),
  "image/x-sony-sr2": const RegistryEntry(
    mediaType: 'image/x-sony-sr2',
    comments: ['Sony SR2 raw image'],
    acronym: 'SR2',
    expandedAcronym: 'Sony Raw format 2',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.sr2', weight: 50, caseSensitive: false)],
  ),
  "image/x-sony-arw": const RegistryEntry(
    mediaType: 'image/x-sony-arw',
    comments: ['Sony ARW raw image'],
    acronym: 'ARW',
    expandedAcronym: 'Alpha Raw format',
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.arw', weight: 50, caseSensitive: false)],
  ),
  "image/png": const RegistryEntry(
    mediaType: 'image/png',
    comments: ['PNG image'],
    acronym: 'PNG',
    expandedAcronym: 'Portable Network Graphics',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.png', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x89PNG\r\n\x1a\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/apng": const RegistryEntry(
    mediaType: 'image/apng',
    comments: ['Animated PNG image'],
    acronym: 'PNG',
    expandedAcronym: 'Portable Network Graphics',
    subclassOf: ['image/png'],
    alias: ['image/vnd.mozilla.apng'],
    globs: [
      Glob(pattern: '*.apng', weight: 50, caseSensitive: false),
      Glob(pattern: '*.png', weight: 40, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 60,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x89PNG\r\n\x1a\n',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '37',
                value: 'acTL',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/rle": const RegistryEntry(
    mediaType: 'image/rle',
    comments: ['RLE bitmap image'],
    acronym: 'RLE',
    expandedAcronym: 'Run Length Encoded',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.rle', weight: 50, caseSensitive: false)],
  ),
  "image/svg+xml": const RegistryEntry(
    mediaType: 'image/svg+xml',
    comments: ['SVG image'],
    acronym: 'SVG',
    expandedAcronym: 'Scalable Vector Graphics',
    subclassOf: ['application/xml'],
    alias: [],
    globs: [Glob(pattern: '*.svg', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0:256',
            value: '<!DOCTYPE svg',
            mask: null,
          ),
        ],
      ),
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '<!-- Created with Inkscape',
            mask: null,
          ),
          Match(type: MatchType.string, offset: '0', value: '<svg', mask: null),
        ],
      ),
      Magic(
        priority: 45,
        matches: [
          Match(
            type: MatchType.string,
            offset: '1:256',
            value: '<svg',
            mask: null,
          ),
        ],
      ),
    ],
    rootXML: [
      RootXML(namespaceURI: 'http://www.w3.org/2000/svg', localName: 'svg'),
    ],
  ),
  "image/svg+xml-compressed": const RegistryEntry(
    mediaType: 'image/svg+xml-compressed',
    comments: ['Compressed SVG image'],
    acronym: 'SVG',
    expandedAcronym: 'Scalable Vector Graphics',
    subclassOf: ['application/gzip'],
    alias: [],
    globs: [
      Glob(pattern: '*.svgz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.svg.gz', weight: 50, caseSensitive: false),
    ],
  ),
  "image/tiff": const RegistryEntry(
    mediaType: 'image/tiff',
    comments: ['TIFF image'],
    acronym: 'TIFF',
    expandedAcronym: 'Tagged Image File Format',
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.tif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.tiff', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'MM\x00*',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'II*\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-tiff-multipage": const RegistryEntry(
    mediaType: 'image/x-tiff-multipage',
    comments: ['Multi-page TIFF image'],
    acronym: 'TIFF',
    expandedAcronym: 'Tagged Image File Format',
    subclassOf: ['image/tiff'],
    alias: [],
  ),
  "image/vnd.dwg": const RegistryEntry(
    mediaType: 'image/vnd.dwg',
    comments: ['AutoCAD image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.dwg', weight: 50, caseSensitive: false)],
  ),
  "image/vnd.dxf": const RegistryEntry(
    mediaType: 'image/vnd.dxf',
    comments: ['DXF vector image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.dxf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '\nHEADER\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '\r\nHEADER\r\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/vnd.ms-modi": const RegistryEntry(
    mediaType: 'image/vnd.ms-modi',
    comments: ['MDI image'],
    acronym: 'MDI',
    expandedAcronym: 'Microsoft Document Imaging',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.mdi', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'EP*\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/jxr": const RegistryEntry(
    mediaType: 'image/jxr',
    comments: ['JPEG XR image'],
    acronym: 'XR',
    expandedAcronym: 'Extended Range',
    subclassOf: [],
    alias: ['image/vnd.ms-photo'],
    globs: [
      Glob(pattern: '*.jxr', weight: 50, caseSensitive: false),
      Glob(pattern: '*.hdp', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wdp', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'II\xbc\x01',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/webp": const RegistryEntry(
    mediaType: 'image/webp',
    comments: ['WebP image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.webp', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'RIFF',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '8',
                value: 'WEBP',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-3ds": const RegistryEntry(
    mediaType: 'image/x-3ds',
    comments: ['3D Studio image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.3ds', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 30,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0x4d4d',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-applix-graphics": const RegistryEntry(
    mediaType: 'image/x-applix-graphics',
    comments: ['Applix Graphics image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ag', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '*BEGIN',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '7',
                value: 'GRAPHICS',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-bzeps": const RegistryEntry(
    mediaType: 'image/x-bzeps',
    comments: ['EPS image (bzip2-compressed)'],
    subclassOf: ['application/x-bzip2'],
    alias: [],
    globs: [
      Glob(pattern: '*.eps.bz2', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsi.bz2', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsf.bz2', weight: 50, caseSensitive: false),
    ],
  ),
  "image/x-cmu-raster": const RegistryEntry(
    mediaType: 'image/x-cmu-raster',
    comments: ['CMU raster image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ras', weight: 50, caseSensitive: false)],
  ),
  "image/x-compressed-xcf": const RegistryEntry(
    mediaType: 'image/x-compressed-xcf',
    comments: ['Compressed GIMP image'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.xcf.gz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.xcf.bz2', weight: 50, caseSensitive: false),
    ],
  ),
  "image/x-dib": const RegistryEntry(
    mediaType: 'image/x-dib',
    comments: ['DIB image'],
    acronym: 'DIB',
    expandedAcronym: 'Device Independent Bitmap',
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '(\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/vnd.djvu": const RegistryEntry(
    mediaType: 'image/vnd.djvu',
    comments: ['DjVu image'],
    subclassOf: [],
    alias: ['image/x-djvu', 'image/x.djvu'],
    globs: [
      Glob(pattern: '*.djvu', weight: 50, caseSensitive: false),
      Glob(pattern: '*.djv', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'AT&TFORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '12',
                value: 'DJVU',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '8',
                value: 'DJVU',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/vnd.djvu+multipage": const RegistryEntry(
    mediaType: 'image/vnd.djvu+multipage',
    genericIcon: GenericIcon.xOfficeDocument,
    comments: ['DjVu document'],
    subclassOf: ['image/vnd.djvu'],
    alias: [],
    globs: [
      Glob(pattern: '*.djvu', weight: 50, caseSensitive: false),
      Glob(pattern: '*.djv', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'AT&TFORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '12',
                value: 'DJVM',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '8',
                value: 'DJVM',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/dpx": const RegistryEntry(
    mediaType: 'image/dpx',
    comments: ['DPX image'],
    acronym: 'DPX',
    expandedAcronym: 'Digital Moving Picture Exchange',
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x53445058',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-eps": const RegistryEntry(
    mediaType: 'image/x-eps',
    comments: ['EPS image'],
    acronym: 'EPS',
    expandedAcronym: 'Encapsulated PostScript',
    subclassOf: ['application/postscript'],
    alias: [],
    globs: [
      Glob(pattern: '*.eps', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsi', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsf', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 90,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '%!',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '15',
                value: 'EPS',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x04%!',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '16',
                value: 'EPS',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xC5D0D3C6',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-fpx": const RegistryEntry(
    mediaType: 'image/x-fpx',
    comments: ['FPX image'],
    acronym: 'FPX',
    expandedAcronym: 'FlashPiX',
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x46506978',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-gzeps": const RegistryEntry(
    mediaType: 'image/x-gzeps',
    comments: ['EPS image (gzip-compressed)'],
    subclassOf: ['application/gzip'],
    alias: [],
    globs: [
      Glob(pattern: '*.eps.gz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsi.gz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsf.gz', weight: 50, caseSensitive: false),
    ],
  ),
  "image/vnd.microsoft.icon": const RegistryEntry(
    mediaType: 'image/vnd.microsoft.icon',
    comments: ['Windows icon'],
    subclassOf: [],
    alias: [
      'application/ico',
      'image/ico',
      'image/icon',
      'image/x-ico',
      'image/x-icon',
      'text/ico',
    ],
    globs: [Glob(pattern: '*.ico', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x01\x00',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '5',
                value: '\x00',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-icns": const RegistryEntry(
    mediaType: 'image/x-icns',
    comments: ['MacOS X icon'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.icns', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'icns', mask: null),
        ],
      ),
    ],
  ),
  "image/x-ilbm": const RegistryEntry(
    mediaType: 'image/x-ilbm',
    comments: ['ILBM image'],
    acronym: 'ILBM',
    expandedAcronym: 'InterLeaved BitMap',
    subclassOf: ['application/x-iff'],
    alias: ['image/x-iff'],
    globs: [
      Glob(pattern: '*.iff', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ilbm', weight: 50, caseSensitive: false),
      Glob(pattern: '*.lbm', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '8', value: 'ILBM', mask: null),
          Match(type: MatchType.string, offset: '8', value: 'PBM ', mask: null),
        ],
      ),
    ],
  ),
  "image/x-jng": const RegistryEntry(
    mediaType: 'image/x-jng',
    comments: ['JNG image'],
    acronym: 'JNG',
    expandedAcronym: 'JPEG Network Graphics',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.jng', weight: 50, caseSensitive: false)],
  ),
  "image/x-lwo": const RegistryEntry(
    mediaType: 'image/x-lwo',
    comments: ['LightWave object'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.lwo', weight: 50, caseSensitive: false),
      Glob(pattern: '*.lwob', weight: 50, caseSensitive: false),
    ],
  ),
  "image/x-lws": const RegistryEntry(
    mediaType: 'image/x-lws',
    comments: ['LightWave scene'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.lws', weight: 50, caseSensitive: false)],
  ),
  "image/x-macpaint": const RegistryEntry(
    mediaType: 'image/x-macpaint',
    comments: ['MacPaint Bitmap image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pntg', weight: 50, caseSensitive: false)],
  ),
  "image/x-msod": const RegistryEntry(
    mediaType: 'image/x-msod',
    comments: ['Office drawing'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.msod', weight: 50, caseSensitive: false)],
  ),
  "image/x-niff": const RegistryEntry(
    mediaType: 'image/x-niff',
    comments: ['NIFF image'],
    acronym: 'NIFF',
    expandedAcronym: 'Navy Image File Format',
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'IIN1', mask: null),
        ],
      ),
    ],
  ),
  "image/vnd.zbrush.pcx": const RegistryEntry(
    mediaType: 'image/vnd.zbrush.pcx',
    comments: ['PCX image'],
    acronym: 'PCX',
    expandedAcronym: 'PiCture eXchange',
    subclassOf: [],
    alias: ['image/x-pcx'],
    globs: [Glob(pattern: '*.pcx', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.byte,
            offset: '0',
            value: '10',
            mask: null,
            subMatches: [
              Match(type: MatchType.byte, offset: '1', value: '0', mask: null),
              Match(type: MatchType.byte, offset: '1', value: '2', mask: null),
              Match(type: MatchType.byte, offset: '1', value: '3', mask: null),
              Match(type: MatchType.byte, offset: '1', value: '5', mask: null),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-photo-cd": const RegistryEntry(
    mediaType: 'image/x-photo-cd',
    genericIcon: GenericIcon.mediaOptical,
    comments: ['PCD image'],
    acronym: 'PCD',
    expandedAcronym: 'PhotoCD',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pcd', weight: 50, caseSensitive: false)],
  ),
  "image/x-portable-anymap": const RegistryEntry(
    mediaType: 'image/x-portable-anymap',
    comments: ['PNM image'],
    acronym: 'PNM',
    expandedAcronym: 'Portable Anymap',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pnm', weight: 50, caseSensitive: false)],
  ),
  "image/x-portable-bitmap": const RegistryEntry(
    mediaType: 'image/x-portable-bitmap',
    comments: ['PBM image'],
    acronym: 'PBM',
    expandedAcronym: 'Portable BitMap',
    subclassOf: ['image/x-portable-anymap'],
    alias: [],
    globs: [Glob(pattern: '*.pbm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P1',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P4',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-portable-graymap": const RegistryEntry(
    mediaType: 'image/x-portable-graymap',
    comments: ['PGM image'],
    acronym: 'PGM',
    expandedAcronym: 'Portable GrayMap',
    subclassOf: ['image/x-portable-anymap'],
    alias: [],
    globs: [Glob(pattern: '*.pgm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P2',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P5',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-portable-pixmap": const RegistryEntry(
    mediaType: 'image/x-portable-pixmap',
    comments: ['PPM image'],
    acronym: 'PPM',
    expandedAcronym: 'Portable PixMap',
    subclassOf: ['image/x-portable-anymap'],
    alias: [],
    globs: [Glob(pattern: '*.ppm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P3',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P6',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/vnd.adobe.photoshop": const RegistryEntry(
    mediaType: 'image/vnd.adobe.photoshop',
    comments: ['Photoshop image'],
    subclassOf: [],
    alias: [
      'image/psd',
      'image/x-psd',
      'image/photoshop',
      'image/x-photoshop',
      'application/photoshop',
      'application/x-photoshop',
    ],
    globs: [Glob(pattern: '*.psd', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '8BPS  \x00\x00\x00\x00',
            mask: '0xffffffff0000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/x-rgb": const RegistryEntry(
    mediaType: 'image/x-rgb',
    comments: ['RGB image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.rgb', weight: 50, caseSensitive: false)],
  ),
  "image/x-sgi": const RegistryEntry(
    mediaType: 'image/x-sgi',
    comments: ['SGI image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.sgi', weight: 50, caseSensitive: false)],
  ),
  "image/x-sun-raster": const RegistryEntry(
    mediaType: 'image/x-sun-raster',
    comments: ['Sun raster image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.sun', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x59a66a95',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-tga": const RegistryEntry(
    mediaType: 'image/x-tga',
    comments: ['TGA image'],
    acronym: 'TGA',
    expandedAcronym: 'Truevision Graphics Adapter',
    subclassOf: [],
    alias: [
      'application/tga',
      'application/x-targa',
      'application/x-tga',
      'image/targa',
      'image/tga',
      'image/x-icb',
      'image/x-targa',
    ],
    globs: [
      Glob(pattern: '*.tga', weight: 50, caseSensitive: false),
      Glob(pattern: '*.icb', weight: 50, caseSensitive: false),
      Glob(pattern: '*.tpic', weight: 50, caseSensitive: false),
      Glob(pattern: '*.vda', weight: 50, caseSensitive: false),
      Glob(pattern: '*.vst', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 10,
        matches: [
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x01\x01',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x01\t',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\x03',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\\xa',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\\xb',
            mask: null,
          ),
        ],
      ),
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\x02',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x08',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x10',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x18',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x20',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-win-bitmap": const RegistryEntry(
    mediaType: 'image/x-win-bitmap',
    comments: ['Windows cursor'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.cur', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x02\x00',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '5',
                value: '\x00',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/emf": const RegistryEntry(
    mediaType: 'image/emf',
    comments: ['EMF image'],
    acronym: 'EMF',
    expandedAcronym: 'Enhanced MetaFile',
    subclassOf: [],
    alias: ['image/x-emf', 'application/x-emf', 'application/emf'],
    globs: [Glob(pattern: '*.emf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x00000001',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little32,
                offset: '40',
                value: '0x464D4520',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.little32,
                    offset: '44',
                    value: '0x00010000',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.little16,
                        offset: '58',
                        value: '0x0000',
                        mask: null,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/wmf": const RegistryEntry(
    mediaType: 'image/wmf',
    comments: ['WMF image'],
    acronym: 'WMF',
    expandedAcronym: 'Windows Metafile',
    subclassOf: [],
    alias: [
      'image/x-wmf',
      'image/x-win-metafile',
      'application/x-wmf',
      'application/wmf',
      'application/x-msmetafile',
    ],
    globs: [Glob(pattern: '*.wmf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x9AC6CDD7',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little16,
                offset: '22',
                value: '0x0001',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.little16,
                    offset: '24',
                    value: '0x0009',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
          Match(
            type: MatchType.little16,
            offset: '0',
            value: '0x0001',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little16,
                offset: '2',
                value: '0x0009',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-xbitmap": const RegistryEntry(
    mediaType: 'image/x-xbitmap',
    comments: ['XBM image'],
    acronym: 'XBM',
    expandedAcronym: 'X BitMap',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xbm', weight: 50, caseSensitive: false)],
  ),
  "image/x-xcf": const RegistryEntry(
    mediaType: 'image/x-xcf',
    comments: ['GIMP image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xcf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'gimp xcf file',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'gimp xcf v',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-gimp-gbr": const RegistryEntry(
    mediaType: 'image/x-gimp-gbr',
    comments: ['GIMP brush'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gbr', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '20',
            value: 'GIMP',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-gimp-gih": const RegistryEntry(
    mediaType: 'image/x-gimp-gih',
    comments: ['GIMP brush pipe'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gih', weight: 50, caseSensitive: false)],
  ),
  "image/x-gimp-pat": const RegistryEntry(
    mediaType: 'image/x-gimp-pat',
    comments: ['GIMP pattern'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pat', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '20',
            value: 'GPAT',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-xfig": const RegistryEntry(
    mediaType: 'image/x-xfig',
    comments: ['XFig image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.fig', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: '#FIG', mask: null),
        ],
      ),
    ],
  ),
  "image/x-xpixmap": const RegistryEntry(
    mediaType: 'image/x-xpixmap',
    comments: ['XPM image'],
    acronym: 'XPM',
    expandedAcronym: 'X PixMap',
    subclassOf: [],
    alias: ['image/x-xpm'],
    globs: [Glob(pattern: '*.xpm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '/* XPM */',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '! XPM2\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-xwindowdump": const RegistryEntry(
    mediaType: 'image/x-xwindowdump',
    comments: ['X window image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xwd', weight: 50, caseSensitive: false)],
  ),
  "image/x-quicktime": const RegistryEntry(
    mediaType: 'image/x-quicktime',
    comments: ['QuickTime image'],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.qtif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.qif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '4', value: 'idat', mask: null),
        ],
      ),
    ],
  ),
  "image/ktx": const RegistryEntry(
    mediaType: 'image/ktx',
    comments: ['Khronos texture image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ktx', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xAB4B5458',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big32,
                offset: '4',
                value: '0x203131BB',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big32,
                    offset: '8',
                    value: '0x0D0A1A0A',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/ktx2": const RegistryEntry(
    mediaType: 'image/ktx2',
    comments: ['Khronos texture image'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ktx2', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xAB4B5458',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big32,
                offset: '4',
                value: '0x203230BB',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big32,
                    offset: '8',
                    value: '0x0D0A1A0A',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/astc": const RegistryEntry(
    mediaType: 'image/astc',
    comments: ['ASTC texture'],
    acronym: 'ASTC',
    expandedAcronym: 'Advanced Scalable Texture Compression',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.astc', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x5CA1AB13',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/avif": const RegistryEntry(
    mediaType: 'image/avif',
    comments: ['AVIF image'],
    acronym: 'AVIF',
    expandedAcronym: 'AV1 Image File Format',
    subclassOf: [],
    alias: ['image/avif-sequence'],
    globs: [
      Glob(pattern: '*.avif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.avifs', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypavif',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypavis',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypmif1',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '16',
                value: 'avif',
                mask: null,
              ),
              Match(
                type: MatchType.string,
                offset: '20',
                value: 'avif',
                mask: null,
              ),
              Match(
                type: MatchType.string,
                offset: '24',
                value: 'avif',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/qoi": const RegistryEntry(
    mediaType: 'image/qoi',
    comments: ['Quite OK Image Format'],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.qoi', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'qoif', mask: null),
        ],
      ),
    ],
  ),
};
