/*
Copyright 2026 The KMDB Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names

import '../registry_base.dart';
import 'package:kmdb_util/util.dart';
import 'package:meta/meta.dart';

@internal
final Map<String, RegistryEntry> mimeinfoDbX_content = {
  "x-content/image-dcf": const RegistryEntry(
    mediaType: 'x-content/image-dcf',
    comments: [IntlString.constant('Digital photos')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/video-vcd": const RegistryEntry(
    mediaType: 'x-content/video-vcd',
    comments: [IntlString.constant('Video CD')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/video-svcd": const RegistryEntry(
    mediaType: 'x-content/video-svcd',
    comments: [IntlString.constant('Super Video CD')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/video-dvd": const RegistryEntry(
    mediaType: 'x-content/video-dvd',
    comments: [IntlString.constant('Video DVD')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/audio-cdda": const RegistryEntry(
    mediaType: 'x-content/audio-cdda',
    comments: [IntlString.constant('Audio CD')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/blank-cd": const RegistryEntry(
    mediaType: 'x-content/blank-cd',
    comments: [IntlString.constant('Blank CD disc')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/blank-dvd": const RegistryEntry(
    mediaType: 'x-content/blank-dvd',
    comments: [IntlString.constant('Blank DVD disc')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/blank-bd": const RegistryEntry(
    mediaType: 'x-content/blank-bd',
    comments: [IntlString.constant('Blank Blu-ray disc')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/blank-hddvd": const RegistryEntry(
    mediaType: 'x-content/blank-hddvd',
    comments: [IntlString.constant('Blank HD DVD disc')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/audio-dvd": const RegistryEntry(
    mediaType: 'x-content/audio-dvd',
    comments: [IntlString.constant('Audio DVD')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/video-bluray": const RegistryEntry(
    mediaType: 'x-content/video-bluray',
    comments: [IntlString.constant('Blu-ray video disc')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/video-hddvd": const RegistryEntry(
    mediaType: 'x-content/video-hddvd',
    comments: [IntlString.constant('HD DVD video disc')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/ebook-reader": const RegistryEntry(
    mediaType: 'x-content/ebook-reader',
    comments: [IntlString.constant('E-book reader')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/image-picturecd": const RegistryEntry(
    mediaType: 'x-content/image-picturecd',
    comments: [IntlString.constant('Picture CD')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/audio-player": const RegistryEntry(
    mediaType: 'x-content/audio-player',
    comments: [IntlString.constant('Portable audio player')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/ostree-repository": const RegistryEntry(
    mediaType: 'x-content/ostree-repository',
    comments: [IntlString.constant('OSTree software updates')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/software": const RegistryEntry(
    mediaType: 'x-content/software',
    comments: [IntlString.constant('Software')],
    subclassOf: [],
    alias: [],
  ),
  "x-content/unix-software": const RegistryEntry(
    mediaType: 'x-content/unix-software',
    comments: [IntlString.constant('UNIX software')],
    subclassOf: ['x-content/software'],
    alias: [],
  ),
  "x-content/win32-software": const RegistryEntry(
    mediaType: 'x-content/win32-software',
    comments: [IntlString.constant('Windows software')],
    subclassOf: ['x-content/software'],
    alias: [],
  ),
};
