/*
Copyright 2026 The KMDB Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names

import '../registry_base.dart';
import 'package:kmdb_util/util.dart';
import 'package:meta/meta.dart';

@internal
final Map<String, RegistryEntry> mimeinfoDbImage = {
  "image/x-skencil": const RegistryEntry(
    mediaType: 'image/x-skencil',
    comments: [IntlString.constant('Skencil document')],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.sk', weight: 50, caseSensitive: false),
      Glob(pattern: '*.sk1', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '##Sketch',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/vnd.rn-realpix": const RegistryEntry(
    mediaType: 'image/vnd.rn-realpix',
    comments: [IntlString.constant('RealPix document')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.rp', weight: 50, caseSensitive: false)],
  ),
  "image/bmp": const RegistryEntry(
    mediaType: 'image/bmp',
    comments: [IntlString.constant('Windows BMP image')],
    subclassOf: [],
    alias: ['image/x-bmp', 'image/x-MS-bmp'],
    globs: [
      Glob(pattern: '*.bmp', weight: 50, caseSensitive: false),
      Glob(pattern: '*.dib', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'BMxxxx\x00\x00',
            mask: '0xffff00000000ffff',
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'BM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '14',
                value: '12',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '14',
                value: '64',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '14',
                value: '40',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/vnd.wap.wbmp": const RegistryEntry(
    mediaType: 'image/vnd.wap.wbmp',
    comments: [IntlString.constant('WBMP image')],
    acronym: IntlString.constant('WBMP'),
    expandedAcronym: IntlString.constant('WAP bitmap'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.wbmp', weight: 50, caseSensitive: false)],
  ),
  "image/cgm": const RegistryEntry(
    mediaType: 'image/cgm',
    comments: [IntlString.constant('CGM image')],
    acronym: IntlString.constant('CGM'),
    expandedAcronym: IntlString.constant('Computer Graphics Metafile'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.cgm', weight: 50, caseSensitive: false)],
  ),
  "image/g3fax": const RegistryEntry(
    mediaType: 'image/g3fax',
    comments: [IntlString.constant('CCITT G3 fax image')],
    acronym: IntlString.constant('CCITT'),
    expandedAcronym: IntlString.constant(
      'Comit\xe9 Consultatif International T\xe9l\xe9phonique et T\xe9l\xe9graphique',
    ),
    subclassOf: [],
    alias: ['image/fax-g3'],
    globs: [Glob(pattern: '*.g3', weight: 50, caseSensitive: false)],
  ),
  "image/gif": const RegistryEntry(
    mediaType: 'image/gif',
    comments: [IntlString.constant('GIF image')],
    acronym: IntlString.constant('GIF'),
    expandedAcronym: IntlString.constant('Graphics Interchange Format'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gif', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'GIF8', mask: null),
        ],
      ),
    ],
  ),
  "image/heif": const RegistryEntry(
    mediaType: 'image/heif',
    comments: [IntlString.constant('HEIF image')],
    acronym: IntlString.constant('HEIF'),
    expandedAcronym: IntlString.constant('High Efficiency Image File'),
    subclassOf: [],
    alias: ['image/heic', 'image/heic-sequence', 'image/heif-sequence'],
    globs: [
      Glob(pattern: '*.heic', weight: 50, caseSensitive: false),
      Glob(pattern: '*.heif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.hif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 40,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypmif1',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypmsf1',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypheic',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypheix',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftyphevc',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftyphevx',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/ief": const RegistryEntry(
    mediaType: 'image/ief',
    comments: [IntlString.constant('IEF image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ief', weight: 50, caseSensitive: false)],
  ),
  "image/jpeg": const RegistryEntry(
    mediaType: 'image/jpeg',
    comments: [IntlString.constant('JPEG image')],
    acronym: IntlString.constant('JPEG'),
    expandedAcronym: IntlString.constant('Joint Photographic Experts Group'),
    subclassOf: [],
    alias: ['image/pjpeg'],
    globs: [
      Glob(pattern: '*.jpg', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpeg', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpe', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jfif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\xff\xd8\xff',
            mask: null,
          ),
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0xffd8',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-jp2-codestream": const RegistryEntry(
    mediaType: 'image/x-jp2-codestream',
    comments: [IntlString.constant('JPEG-2000 codestream')],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.j2c', weight: 50, caseSensitive: false),
      Glob(pattern: '*.j2k', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpc', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xff4fff51',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/jp2": const RegistryEntry(
    mediaType: 'image/jp2',
    comments: [IntlString.constant('JPEG-2000 JP2 image')],
    acronym: IntlString.constant('JP2'),
    expandedAcronym: IntlString.constant('JPEG-2000'),
    subclassOf: [],
    alias: ['image/jpeg2000', 'image/jpeg2000-image', 'image/x-jpeg2000-image'],
    globs: [
      Glob(pattern: '*.jp2', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpg2', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fjP  \r\n\x87\n        jp2 ',
            mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/jpx": const RegistryEntry(
    mediaType: 'image/jpx',
    comments: [IntlString.constant('JPEG-2000 JPX image')],
    acronym: IntlString.constant('JPX'),
    expandedAcronym: IntlString.constant('JPEG-2000 eXtended'),
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.jpf', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpx', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fjP  \r\n\x87\n        jpx ',
            mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/jpm": const RegistryEntry(
    mediaType: 'image/jpm',
    comments: [IntlString.constant('JPEG-2000 JPM image')],
    acronym: IntlString.constant('JPM'),
    expandedAcronym: IntlString.constant('JPEG-2000 Mixed'),
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.jpm', weight: 50, caseSensitive: false),
      Glob(pattern: '*.jpgm', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fjP  \r\n\x87\n        jpm ',
            mask: '0xffffffffffffffffffffffff0000000000000000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/jxl": const RegistryEntry(
    mediaType: 'image/jxl',
    comments: [IntlString.constant('JPEG XL image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.jxl', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\xff\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x00\fJXL \r\n\x87\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/openraster": const RegistryEntry(
    mediaType: 'image/openraster',
    comments: [IntlString.constant('OpenRaster image')],
    subclassOf: ['application/zip'],
    alias: [],
    globs: [Glob(pattern: '*.ora', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 70,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'PK\x03\x04',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '30',
                value: 'mimetype',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.string,
                    offset: '38',
                    value: 'image/openraster',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-dds": const RegistryEntry(
    mediaType: 'image/x-dds',
    comments: [IntlString.constant('DirectDraw surface')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.dds', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'DDS', mask: null),
        ],
      ),
    ],
  ),
  "image/x-xcursor": const RegistryEntry(
    mediaType: 'image/x-xcursor',
    comments: [IntlString.constant('X11 cursor')],
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'Xcur', mask: null),
        ],
      ),
    ],
  ),
  "image/x-exr": const RegistryEntry(
    mediaType: 'image/x-exr',
    comments: [IntlString.constant('EXR image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.exr', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '20000630',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-pict": const RegistryEntry(
    mediaType: 'image/x-pict',
    comments: [IntlString.constant('Macintosh Quickdraw/PICT drawing')],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.pct', weight: 50, caseSensitive: false),
      Glob(pattern: '*.pict', weight: 50, caseSensitive: false),
      Glob(pattern: '*.pict1', weight: 50, caseSensitive: false),
      Glob(pattern: '*.pict2', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '10',
            value: '0x0011',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big16,
                offset: '12',
                value: '0x02FF',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big16,
                    offset: '14',
                    value: '0x0C00',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.big16,
                        offset: '16',
                        value: '0xFFFE',
                        mask: null,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '522',
            value: '0x0011',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big16,
                offset: '524',
                value: '0x02FF',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big16,
                    offset: '526',
                    value: '0x0C00',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.big16,
                        offset: '528',
                        value: '0xFFFE',
                        mask: null,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-dcraw": const RegistryEntry(
    mediaType: 'image/x-dcraw',
    comments: [IntlString.constant('Digital raw image')],
    subclassOf: [],
    alias: [],
  ),
  "image/x-adobe-dng": const RegistryEntry(
    mediaType: 'image/x-adobe-dng',
    comments: [IntlString.constant('Adobe DNG negative')],
    acronym: IntlString.constant('DNG'),
    expandedAcronym: IntlString.constant('Digital Negative'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.dng', weight: 50, caseSensitive: false)],
  ),
  "image/x-canon-crw": const RegistryEntry(
    mediaType: 'image/x-canon-crw',
    comments: [IntlString.constant('Canon CRW raw image')],
    acronym: IntlString.constant('CRW'),
    expandedAcronym: IntlString.constant('Canon RaW'),
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.crw', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'II\x1a\x00\x00\x00HEAPCCDR',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-canon-cr2": const RegistryEntry(
    mediaType: 'image/x-canon-cr2',
    comments: [IntlString.constant('Canon CR2 raw image')],
    acronym: IntlString.constant('CR2'),
    expandedAcronym: IntlString.constant('Canon Raw 2'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.cr2', weight: 50, caseSensitive: false)],
  ),
  "image/x-canon-cr3": const RegistryEntry(
    mediaType: 'image/x-canon-cr3',
    comments: [IntlString.constant('Canon CR3 raw image')],
    acronym: IntlString.constant('CR3'),
    expandedAcronym: IntlString.constant('Canon Raw 3'),
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.cr3', weight: 50, caseSensitive: false)],
  ),
  "image/x-fuji-raf": const RegistryEntry(
    mediaType: 'image/x-fuji-raf',
    comments: [IntlString.constant('Fuji RAF raw image')],
    acronym: IntlString.constant('RAF'),
    expandedAcronym: IntlString.constant('RAw Format'),
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.raf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FUJIFILMCCD-RAW ',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-kodak-dcr": const RegistryEntry(
    mediaType: 'image/x-kodak-dcr',
    comments: [IntlString.constant('Kodak DCR raw image')],
    acronym: IntlString.constant('DCR'),
    expandedAcronym: IntlString.constant('Digital Camera Raw'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.dcr', weight: 50, caseSensitive: false)],
  ),
  "image/x-kodak-k25": const RegistryEntry(
    mediaType: 'image/x-kodak-k25',
    comments: [IntlString.constant('Kodak K25 raw image')],
    acronym: IntlString.constant('K25'),
    expandedAcronym: IntlString.constant('Kodak DC25'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.k25', weight: 50, caseSensitive: false)],
  ),
  "image/x-kodak-kdc": const RegistryEntry(
    mediaType: 'image/x-kodak-kdc',
    comments: [IntlString.constant('Kodak KDC raw image')],
    acronym: IntlString.constant('KDC'),
    expandedAcronym: IntlString.constant('Kodak Digital Camera'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.kdc', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '242',
            value: 'EASTMAN KODAK COMPANY',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-minolta-mrw": const RegistryEntry(
    mediaType: 'image/x-minolta-mrw',
    comments: [IntlString.constant('Minolta MRW raw image')],
    acronym: IntlString.constant('MRW'),
    expandedAcronym: IntlString.constant('Minolta RaW'),
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.mrw', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00MRM',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-nikon-nef": const RegistryEntry(
    mediaType: 'image/x-nikon-nef',
    comments: [IntlString.constant('Nikon NEF raw image')],
    acronym: IntlString.constant('NEF'),
    expandedAcronym: IntlString.constant('Nikon Electronic Format'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.nef', weight: 50, caseSensitive: false)],
  ),
  "image/x-nikon-nrw": const RegistryEntry(
    mediaType: 'image/x-nikon-nrw',
    comments: [IntlString.constant('Nikon NRW raw image')],
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.nrw', weight: 50, caseSensitive: false)],
  ),
  "image/x-olympus-orf": const RegistryEntry(
    mediaType: 'image/x-olympus-orf',
    comments: [IntlString.constant('Olympus ORF raw image')],
    acronym: IntlString.constant('ORF'),
    expandedAcronym: IntlString.constant('Olympus Raw Format'),
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.orf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'IIRO\b\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-panasonic-rw": const RegistryEntry(
    mediaType: 'image/x-panasonic-rw',
    comments: [IntlString.constant('Panasonic raw image')],
    subclassOf: ['image/x-dcraw'],
    alias: ['image/x-panasonic-raw'],
    globs: [Glob(pattern: '*.raw', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'IIU\x00\b\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-panasonic-rw2": const RegistryEntry(
    mediaType: 'image/x-panasonic-rw2',
    comments: [IntlString.constant('Panasonic raw image')],
    subclassOf: ['image/x-dcraw'],
    alias: ['image/x-panasonic-raw2'],
    globs: [Glob(pattern: '*.rw2', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'IIU\x00\x18\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-pentax-pef": const RegistryEntry(
    mediaType: 'image/x-pentax-pef',
    comments: [IntlString.constant('Pentax PEF raw image')],
    acronym: IntlString.constant('PEF'),
    expandedAcronym: IntlString.constant('Pentax Electronic Format'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.pef', weight: 50, caseSensitive: false)],
  ),
  "image/x-sigma-x3f": const RegistryEntry(
    mediaType: 'image/x-sigma-x3f',
    comments: [IntlString.constant('Sigma X3F raw image')],
    acronym: IntlString.constant('X3F'),
    expandedAcronym: IntlString.constant('X3 Foveon'),
    subclassOf: ['image/x-dcraw'],
    alias: [],
    globs: [Glob(pattern: '*.x3f', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FOVb',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little32,
                offset: '4',
                value: '0x00FF00FF',
                mask: '0xFF00FF00',
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-sony-srf": const RegistryEntry(
    mediaType: 'image/x-sony-srf',
    comments: [IntlString.constant('Sony SRF raw image')],
    acronym: IntlString.constant('SRF'),
    expandedAcronym: IntlString.constant('Sony Raw Format'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.srf', weight: 50, caseSensitive: false)],
  ),
  "image/x-sony-sr2": const RegistryEntry(
    mediaType: 'image/x-sony-sr2',
    comments: [IntlString.constant('Sony SR2 raw image')],
    acronym: IntlString.constant('SR2'),
    expandedAcronym: IntlString.constant('Sony Raw format 2'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.sr2', weight: 50, caseSensitive: false)],
  ),
  "image/x-sony-arw": const RegistryEntry(
    mediaType: 'image/x-sony-arw',
    comments: [IntlString.constant('Sony ARW raw image')],
    acronym: IntlString.constant('ARW'),
    expandedAcronym: IntlString.constant('Alpha Raw format'),
    subclassOf: ['image/x-dcraw', 'image/tiff'],
    alias: [],
    globs: [Glob(pattern: '*.arw', weight: 50, caseSensitive: false)],
  ),
  "image/png": const RegistryEntry(
    mediaType: 'image/png',
    comments: [IntlString.constant('PNG image')],
    acronym: IntlString.constant('PNG'),
    expandedAcronym: IntlString.constant('Portable Network Graphics'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.png', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x89PNG\r\n\x1a\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/apng": const RegistryEntry(
    mediaType: 'image/apng',
    comments: [IntlString.constant('Animated PNG image')],
    acronym: IntlString.constant('PNG'),
    expandedAcronym: IntlString.constant('Portable Network Graphics'),
    subclassOf: ['image/png'],
    alias: ['image/vnd.mozilla.apng'],
    globs: [
      Glob(pattern: '*.apng', weight: 50, caseSensitive: false),
      Glob(pattern: '*.png', weight: 40, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 60,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x89PNG\r\n\x1a\n',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '37',
                value: 'acTL',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/rle": const RegistryEntry(
    mediaType: 'image/rle',
    comments: [IntlString.constant('RLE bitmap image')],
    acronym: IntlString.constant('RLE'),
    expandedAcronym: IntlString.constant('Run Length Encoded'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.rle', weight: 50, caseSensitive: false)],
  ),
  "image/svg+xml": const RegistryEntry(
    mediaType: 'image/svg+xml',
    comments: [IntlString.constant('SVG image')],
    acronym: IntlString.constant('SVG'),
    expandedAcronym: IntlString.constant('Scalable Vector Graphics'),
    subclassOf: ['application/xml'],
    alias: [],
    globs: [Glob(pattern: '*.svg', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0:256',
            value: '<!DOCTYPE svg',
            mask: null,
          ),
        ],
      ),
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '<!-- Created with Inkscape',
            mask: null,
          ),
          Match(type: MatchType.string, offset: '0', value: '<svg', mask: null),
        ],
      ),
      Magic(
        priority: 45,
        matches: [
          Match(
            type: MatchType.string,
            offset: '1:256',
            value: '<svg',
            mask: null,
          ),
        ],
      ),
    ],
    rootXML: [
      RootXML(namespaceURI: 'http://www.w3.org/2000/svg', localName: 'svg'),
    ],
  ),
  "image/svg+xml-compressed": const RegistryEntry(
    mediaType: 'image/svg+xml-compressed',
    comments: [IntlString.constant('Compressed SVG image')],
    acronym: IntlString.constant('SVG'),
    expandedAcronym: IntlString.constant('Scalable Vector Graphics'),
    subclassOf: ['application/gzip'],
    alias: [],
    globs: [
      Glob(pattern: '*.svgz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.svg.gz', weight: 50, caseSensitive: false),
    ],
  ),
  "image/tiff": const RegistryEntry(
    mediaType: 'image/tiff',
    comments: [IntlString.constant('TIFF image')],
    acronym: IntlString.constant('TIFF'),
    expandedAcronym: IntlString.constant('Tagged Image File Format'),
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.tif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.tiff', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'MM\x00*',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'II*\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-tiff-multipage": const RegistryEntry(
    mediaType: 'image/x-tiff-multipage',
    comments: [IntlString.constant('Multi-page TIFF image')],
    acronym: IntlString.constant('TIFF'),
    expandedAcronym: IntlString.constant('Tagged Image File Format'),
    subclassOf: ['image/tiff'],
    alias: [],
  ),
  "image/vnd.dwg": const RegistryEntry(
    mediaType: 'image/vnd.dwg',
    comments: [IntlString.constant('AutoCAD image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.dwg', weight: 50, caseSensitive: false)],
  ),
  "image/vnd.dxf": const RegistryEntry(
    mediaType: 'image/vnd.dxf',
    comments: [IntlString.constant('DXF vector image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.dxf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '\nHEADER\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: '\r\nHEADER\r\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/vnd.ms-modi": const RegistryEntry(
    mediaType: 'image/vnd.ms-modi',
    comments: [IntlString.constant('MDI image')],
    acronym: IntlString.constant('MDI'),
    expandedAcronym: IntlString.constant('Microsoft Document Imaging'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.mdi', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'EP*\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/jxr": const RegistryEntry(
    mediaType: 'image/jxr',
    comments: [IntlString.constant('JPEG XR image')],
    acronym: IntlString.constant('XR'),
    expandedAcronym: IntlString.constant('Extended Range'),
    subclassOf: [],
    alias: ['image/vnd.ms-photo'],
    globs: [
      Glob(pattern: '*.jxr', weight: 50, caseSensitive: false),
      Glob(pattern: '*.hdp', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wdp', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'II\xbc\x01',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/webp": const RegistryEntry(
    mediaType: 'image/webp',
    comments: [IntlString.constant('WebP image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.webp', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'RIFF',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '8',
                value: 'WEBP',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-3ds": const RegistryEntry(
    mediaType: 'image/x-3ds',
    comments: [IntlString.constant('3D Studio image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.3ds', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 30,
        matches: [
          Match(
            type: MatchType.big16,
            offset: '0',
            value: '0x4d4d',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-applix-graphics": const RegistryEntry(
    mediaType: 'image/x-applix-graphics',
    comments: [IntlString.constant('Applix Graphics image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ag', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '*BEGIN',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '7',
                value: 'GRAPHICS',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-bzeps": const RegistryEntry(
    mediaType: 'image/x-bzeps',
    comments: [IntlString.constant('EPS image (bzip2-compressed)')],
    subclassOf: ['application/x-bzip2'],
    alias: [],
    globs: [
      Glob(pattern: '*.eps.bz2', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsi.bz2', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsf.bz2', weight: 50, caseSensitive: false),
    ],
  ),
  "image/x-cmu-raster": const RegistryEntry(
    mediaType: 'image/x-cmu-raster',
    comments: [IntlString.constant('CMU raster image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ras', weight: 50, caseSensitive: false)],
  ),
  "image/x-compressed-xcf": const RegistryEntry(
    mediaType: 'image/x-compressed-xcf',
    comments: [IntlString.constant('Compressed GIMP image')],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.xcf.gz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.xcf.bz2', weight: 50, caseSensitive: false),
    ],
  ),
  "image/x-dib": const RegistryEntry(
    mediaType: 'image/x-dib',
    comments: [IntlString.constant('DIB image')],
    acronym: IntlString.constant('DIB'),
    expandedAcronym: IntlString.constant('Device Independent Bitmap'),
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '(\x00\x00\x00',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/vnd.djvu": const RegistryEntry(
    mediaType: 'image/vnd.djvu',
    comments: [IntlString.constant('DjVu image')],
    subclassOf: [],
    alias: ['image/x-djvu', 'image/x.djvu'],
    globs: [
      Glob(pattern: '*.djvu', weight: 50, caseSensitive: false),
      Glob(pattern: '*.djv', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'AT&TFORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '12',
                value: 'DJVU',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '8',
                value: 'DJVU',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/vnd.djvu+multipage": const RegistryEntry(
    mediaType: 'image/vnd.djvu+multipage',
    genericIcon: GenericIcon.xOfficeDocument,
    comments: [IntlString.constant('DjVu document')],
    subclassOf: ['image/vnd.djvu'],
    alias: [],
    globs: [
      Glob(pattern: '*.djvu', weight: 50, caseSensitive: false),
      Glob(pattern: '*.djv', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'AT&TFORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '12',
                value: 'DJVM',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'FORM',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '8',
                value: 'DJVM',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/dpx": const RegistryEntry(
    mediaType: 'image/dpx',
    comments: [IntlString.constant('DPX image')],
    acronym: IntlString.constant('DPX'),
    expandedAcronym: IntlString.constant('Digital Moving Picture Exchange'),
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x53445058',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-eps": const RegistryEntry(
    mediaType: 'image/x-eps',
    comments: [IntlString.constant('EPS image')],
    acronym: IntlString.constant('EPS'),
    expandedAcronym: IntlString.constant('Encapsulated PostScript'),
    subclassOf: ['application/postscript'],
    alias: [],
    globs: [
      Glob(pattern: '*.eps', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsi', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsf', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 90,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '%!',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '15',
                value: 'EPS',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x04%!',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '16',
                value: 'EPS',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xC5D0D3C6',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-fpx": const RegistryEntry(
    mediaType: 'image/x-fpx',
    comments: [IntlString.constant('FPX image')],
    acronym: IntlString.constant('FPX'),
    expandedAcronym: IntlString.constant('FlashPiX'),
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x46506978',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-gzeps": const RegistryEntry(
    mediaType: 'image/x-gzeps',
    comments: [IntlString.constant('EPS image (gzip-compressed)')],
    subclassOf: ['application/gzip'],
    alias: [],
    globs: [
      Glob(pattern: '*.eps.gz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsi.gz', weight: 50, caseSensitive: false),
      Glob(pattern: '*.epsf.gz', weight: 50, caseSensitive: false),
    ],
  ),
  "image/vnd.microsoft.icon": const RegistryEntry(
    mediaType: 'image/vnd.microsoft.icon',
    comments: [IntlString.constant('Windows icon')],
    subclassOf: [],
    alias: [
      'application/ico',
      'image/ico',
      'image/icon',
      'image/x-ico',
      'image/x-icon',
      'text/ico',
    ],
    globs: [Glob(pattern: '*.ico', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x01\x00',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '5',
                value: '\x00',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-icns": const RegistryEntry(
    mediaType: 'image/x-icns',
    comments: [IntlString.constant('MacOS X icon')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.icns', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'icns', mask: null),
        ],
      ),
    ],
  ),
  "image/x-ilbm": const RegistryEntry(
    mediaType: 'image/x-ilbm',
    comments: [IntlString.constant('ILBM image')],
    acronym: IntlString.constant('ILBM'),
    expandedAcronym: IntlString.constant('InterLeaved BitMap'),
    subclassOf: ['application/x-iff'],
    alias: ['image/x-iff'],
    globs: [
      Glob(pattern: '*.iff', weight: 50, caseSensitive: false),
      Glob(pattern: '*.ilbm', weight: 50, caseSensitive: false),
      Glob(pattern: '*.lbm', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '8', value: 'ILBM', mask: null),
          Match(type: MatchType.string, offset: '8', value: 'PBM ', mask: null),
        ],
      ),
    ],
  ),
  "image/x-jng": const RegistryEntry(
    mediaType: 'image/x-jng',
    comments: [IntlString.constant('JNG image')],
    acronym: IntlString.constant('JNG'),
    expandedAcronym: IntlString.constant('JPEG Network Graphics'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.jng', weight: 50, caseSensitive: false)],
  ),
  "image/x-lwo": const RegistryEntry(
    mediaType: 'image/x-lwo',
    comments: [IntlString.constant('LightWave object')],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.lwo', weight: 50, caseSensitive: false),
      Glob(pattern: '*.lwob', weight: 50, caseSensitive: false),
    ],
  ),
  "image/x-lws": const RegistryEntry(
    mediaType: 'image/x-lws',
    comments: [IntlString.constant('LightWave scene')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.lws', weight: 50, caseSensitive: false)],
  ),
  "image/x-macpaint": const RegistryEntry(
    mediaType: 'image/x-macpaint',
    comments: [IntlString.constant('MacPaint Bitmap image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pntg', weight: 50, caseSensitive: false)],
  ),
  "image/x-msod": const RegistryEntry(
    mediaType: 'image/x-msod',
    comments: [IntlString.constant('Office drawing')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.msod', weight: 50, caseSensitive: false)],
  ),
  "image/x-niff": const RegistryEntry(
    mediaType: 'image/x-niff',
    comments: [IntlString.constant('NIFF image')],
    acronym: IntlString.constant('NIFF'),
    expandedAcronym: IntlString.constant('Navy Image File Format'),
    subclassOf: [],
    alias: [],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'IIN1', mask: null),
        ],
      ),
    ],
  ),
  "image/vnd.zbrush.pcx": const RegistryEntry(
    mediaType: 'image/vnd.zbrush.pcx',
    comments: [IntlString.constant('PCX image')],
    acronym: IntlString.constant('PCX'),
    expandedAcronym: IntlString.constant('PiCture eXchange'),
    subclassOf: [],
    alias: ['image/x-pcx'],
    globs: [Glob(pattern: '*.pcx', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.byte,
            offset: '0',
            value: '10',
            mask: null,
            subMatches: [
              Match(type: MatchType.byte, offset: '1', value: '0', mask: null),
              Match(type: MatchType.byte, offset: '1', value: '2', mask: null),
              Match(type: MatchType.byte, offset: '1', value: '3', mask: null),
              Match(type: MatchType.byte, offset: '1', value: '5', mask: null),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-photo-cd": const RegistryEntry(
    mediaType: 'image/x-photo-cd',
    genericIcon: GenericIcon.mediaOptical,
    comments: [IntlString.constant('PCD image')],
    acronym: IntlString.constant('PCD'),
    expandedAcronym: IntlString.constant('PhotoCD'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pcd', weight: 50, caseSensitive: false)],
  ),
  "image/x-portable-anymap": const RegistryEntry(
    mediaType: 'image/x-portable-anymap',
    comments: [IntlString.constant('PNM image')],
    acronym: IntlString.constant('PNM'),
    expandedAcronym: IntlString.constant('Portable Anymap'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pnm', weight: 50, caseSensitive: false)],
  ),
  "image/x-portable-bitmap": const RegistryEntry(
    mediaType: 'image/x-portable-bitmap',
    comments: [IntlString.constant('PBM image')],
    acronym: IntlString.constant('PBM'),
    expandedAcronym: IntlString.constant('Portable BitMap'),
    subclassOf: ['image/x-portable-anymap'],
    alias: [],
    globs: [Glob(pattern: '*.pbm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P1',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P4',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-portable-graymap": const RegistryEntry(
    mediaType: 'image/x-portable-graymap',
    comments: [IntlString.constant('PGM image')],
    acronym: IntlString.constant('PGM'),
    expandedAcronym: IntlString.constant('Portable GrayMap'),
    subclassOf: ['image/x-portable-anymap'],
    alias: [],
    globs: [Glob(pattern: '*.pgm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P2',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P5',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-portable-pixmap": const RegistryEntry(
    mediaType: 'image/x-portable-pixmap',
    comments: [IntlString.constant('PPM image')],
    acronym: IntlString.constant('PPM'),
    expandedAcronym: IntlString.constant('Portable PixMap'),
    subclassOf: ['image/x-portable-anymap'],
    alias: [],
    globs: [Glob(pattern: '*.ppm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P3',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'P6',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0a',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x20',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x09',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '2',
                value: '0x0d',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/vnd.adobe.photoshop": const RegistryEntry(
    mediaType: 'image/vnd.adobe.photoshop',
    comments: [IntlString.constant('Photoshop image')],
    subclassOf: [],
    alias: [
      'image/psd',
      'image/x-psd',
      'image/photoshop',
      'image/x-photoshop',
      'application/photoshop',
      'application/x-photoshop',
    ],
    globs: [Glob(pattern: '*.psd', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '8BPS  \x00\x00\x00\x00',
            mask: '0xffffffff0000ffffffff',
          ),
        ],
      ),
    ],
  ),
  "image/x-rgb": const RegistryEntry(
    mediaType: 'image/x-rgb',
    comments: [IntlString.constant('RGB image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.rgb', weight: 50, caseSensitive: false)],
  ),
  "image/x-sgi": const RegistryEntry(
    mediaType: 'image/x-sgi',
    comments: [IntlString.constant('SGI image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.sgi', weight: 50, caseSensitive: false)],
  ),
  "image/x-sun-raster": const RegistryEntry(
    mediaType: 'image/x-sun-raster',
    comments: [IntlString.constant('Sun raster image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.sun', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0x59a66a95',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-tga": const RegistryEntry(
    mediaType: 'image/x-tga',
    comments: [IntlString.constant('TGA image')],
    acronym: IntlString.constant('TGA'),
    expandedAcronym: IntlString.constant('Truevision Graphics Adapter'),
    subclassOf: [],
    alias: [
      'application/tga',
      'application/x-targa',
      'application/x-tga',
      'image/targa',
      'image/tga',
      'image/x-icb',
      'image/x-targa',
    ],
    globs: [
      Glob(pattern: '*.tga', weight: 50, caseSensitive: false),
      Glob(pattern: '*.icb', weight: 50, caseSensitive: false),
      Glob(pattern: '*.tpic', weight: 50, caseSensitive: false),
      Glob(pattern: '*.vda', weight: 50, caseSensitive: false),
      Glob(pattern: '*.vst', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 10,
        matches: [
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x01\x01',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x01\t',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\x03',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\\xa',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\\xb',
            mask: null,
          ),
        ],
      ),
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '1',
            value: '\x00\x02',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x08',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x10',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x18',
                mask: null,
              ),
              Match(
                type: MatchType.byte,
                offset: '16',
                value: '0x20',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-win-bitmap": const RegistryEntry(
    mediaType: 'image/x-win-bitmap',
    comments: [IntlString.constant('Windows cursor')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.cur', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '\x00\x00\x02\x00',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '5',
                value: '\x00',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/emf": const RegistryEntry(
    mediaType: 'image/emf',
    comments: [IntlString.constant('EMF image')],
    acronym: IntlString.constant('EMF'),
    expandedAcronym: IntlString.constant('Enhanced MetaFile'),
    subclassOf: [],
    alias: ['image/x-emf', 'application/x-emf', 'application/emf'],
    globs: [Glob(pattern: '*.emf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x00000001',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little32,
                offset: '40',
                value: '0x464D4520',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.little32,
                    offset: '44',
                    value: '0x00010000',
                    mask: null,
                    subMatches: [
                      Match(
                        type: MatchType.little16,
                        offset: '58',
                        value: '0x0000',
                        mask: null,
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/wmf": const RegistryEntry(
    mediaType: 'image/wmf',
    comments: [IntlString.constant('WMF image')],
    acronym: IntlString.constant('WMF'),
    expandedAcronym: IntlString.constant('Windows Metafile'),
    subclassOf: [],
    alias: [
      'image/x-wmf',
      'image/x-win-metafile',
      'application/x-wmf',
      'application/wmf',
      'application/x-msmetafile',
    ],
    globs: [Glob(pattern: '*.wmf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x9AC6CDD7',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little16,
                offset: '22',
                value: '0x0001',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.little16,
                    offset: '24',
                    value: '0x0009',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
          Match(
            type: MatchType.little16,
            offset: '0',
            value: '0x0001',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.little16,
                offset: '2',
                value: '0x0009',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/x-xbitmap": const RegistryEntry(
    mediaType: 'image/x-xbitmap',
    comments: [IntlString.constant('XBM image')],
    acronym: IntlString.constant('XBM'),
    expandedAcronym: IntlString.constant('X BitMap'),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xbm', weight: 50, caseSensitive: false)],
  ),
  "image/x-xcf": const RegistryEntry(
    mediaType: 'image/x-xcf',
    comments: [IntlString.constant('GIMP image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xcf', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'gimp xcf file',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'gimp xcf v',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-gimp-gbr": const RegistryEntry(
    mediaType: 'image/x-gimp-gbr',
    comments: [IntlString.constant('GIMP brush')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gbr', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '20',
            value: 'GIMP',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-gimp-gih": const RegistryEntry(
    mediaType: 'image/x-gimp-gih',
    comments: [IntlString.constant('GIMP brush pipe')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.gih', weight: 50, caseSensitive: false)],
  ),
  "image/x-gimp-pat": const RegistryEntry(
    mediaType: 'image/x-gimp-pat',
    comments: [IntlString.constant('GIMP pattern')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.pat', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '20',
            value: 'GPAT',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-xfig": const RegistryEntry(
    mediaType: 'image/x-xfig',
    comments: [IntlString.constant('XFig image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.fig', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: '#FIG', mask: null),
        ],
      ),
    ],
  ),
  "image/x-xpixmap": const RegistryEntry(
    mediaType: 'image/x-xpixmap',
    comments: [IntlString.constant('XPM image')],
    acronym: IntlString.constant('XPM'),
    expandedAcronym: IntlString.constant('X PixMap'),
    subclassOf: [],
    alias: ['image/x-xpm'],
    globs: [Glob(pattern: '*.xpm', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '/* XPM */',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: '! XPM2\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/x-xwindowdump": const RegistryEntry(
    mediaType: 'image/x-xwindowdump',
    comments: [IntlString.constant('X window image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.xwd', weight: 50, caseSensitive: false)],
  ),
  "image/x-quicktime": const RegistryEntry(
    mediaType: 'image/x-quicktime',
    comments: [IntlString.constant('QuickTime image')],
    subclassOf: [],
    alias: [],
    globs: [
      Glob(pattern: '*.qtif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.qif', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '4', value: 'idat', mask: null),
        ],
      ),
    ],
  ),
  "image/ktx": const RegistryEntry(
    mediaType: 'image/ktx',
    comments: [IntlString.constant('Khronos texture image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ktx', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xAB4B5458',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big32,
                offset: '4',
                value: '0x203131BB',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big32,
                    offset: '8',
                    value: '0x0D0A1A0A',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/ktx2": const RegistryEntry(
    mediaType: 'image/ktx2',
    comments: [IntlString.constant('Khronos texture image')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.ktx2', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.big32,
            offset: '0',
            value: '0xAB4B5458',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.big32,
                offset: '4',
                value: '0x203230BB',
                mask: null,
                subMatches: [
                  Match(
                    type: MatchType.big32,
                    offset: '8',
                    value: '0x0D0A1A0A',
                    mask: null,
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/astc": const RegistryEntry(
    mediaType: 'image/astc',
    comments: [IntlString.constant('ASTC texture')],
    acronym: IntlString.constant('ASTC'),
    expandedAcronym: IntlString.constant(
      'Advanced Scalable Texture Compression',
    ),
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.astc', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 80,
        matches: [
          Match(
            type: MatchType.little32,
            offset: '0',
            value: '0x5CA1AB13',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "image/avif": const RegistryEntry(
    mediaType: 'image/avif',
    comments: [IntlString.constant('AVIF image')],
    acronym: IntlString.constant('AVIF'),
    expandedAcronym: IntlString.constant('AV1 Image File Format'),
    subclassOf: [],
    alias: ['image/avif-sequence'],
    globs: [
      Glob(pattern: '*.avif', weight: 50, caseSensitive: false),
      Glob(pattern: '*.avifs', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypavif',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypavis',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '4',
            value: 'ftypmif1',
            mask: null,
            subMatches: [
              Match(
                type: MatchType.string,
                offset: '16',
                value: 'avif',
                mask: null,
              ),
              Match(
                type: MatchType.string,
                offset: '20',
                value: 'avif',
                mask: null,
              ),
              Match(
                type: MatchType.string,
                offset: '24',
                value: 'avif',
                mask: null,
              ),
            ],
          ),
        ],
      ),
    ],
  ),
  "image/qoi": const RegistryEntry(
    mediaType: 'image/qoi',
    comments: [IntlString.constant('Quite OK Image Format')],
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.qoi', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'qoif', mask: null),
        ],
      ),
    ],
  ),
};
