/*
Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// Generated by tool/loader.dart
// ignore_for_file: non_constant_identifier_names

import '../registry_base.dart';
import 'package:meta/meta.dart';

@internal
final Map<String, RegistryEntry> mimeinfoDbModel = {
  "model/iges": const RegistryEntry(
    mediaType: 'model/iges',
    genericIcon: GenericIcon.xOfficeDocument,
    comments: ['IGES document'],
    acronym: 'IGES',
    expandedAcronym: 'Initial Graphics Exchange Specification',
    subclassOf: ['text/plain'],
    alias: [],
    globs: [
      Glob(pattern: '*.igs', weight: 50, caseSensitive: false),
      Glob(pattern: '*.iges', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '72',
            value: 'S      1\n',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '72',
            value: 'S0000001\n',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "model/gltf-binary": const RegistryEntry(
    mediaType: 'model/gltf-binary',
    genericIcon: GenericIcon.imageXGeneric,
    comments: ['glTF model'],
    acronym: 'glTF',
    expandedAcronym: 'GL Transmission Format',
    subclassOf: [],
    alias: [],
    globs: [Glob(pattern: '*.glb', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(type: MatchType.string, offset: '0', value: 'glTF', mask: null),
        ],
      ),
    ],
  ),
  "model/gltf+json": const RegistryEntry(
    mediaType: 'model/gltf+json',
    genericIcon: GenericIcon.imageXGeneric,
    comments: ['glTF model'],
    acronym: 'glTF',
    expandedAcronym: 'GL Transmission Format',
    subclassOf: ['application/json'],
    alias: [],
    globs: [Glob(pattern: '*.gltf', weight: 50, caseSensitive: false)],
  ),
  "model/vrml": const RegistryEntry(
    mediaType: 'model/vrml',
    genericIcon: GenericIcon.xOfficeDocument,
    comments: ['VRML document'],
    acronym: 'VRML',
    expandedAcronym: 'Virtual Reality Modeling Language',
    subclassOf: ['text/plain'],
    alias: [],
    globs: [
      Glob(pattern: '*.vrm', weight: 50, caseSensitive: false),
      Glob(pattern: '*.vrml', weight: 50, caseSensitive: false),
      Glob(pattern: '*.wrl', weight: 50, caseSensitive: false),
    ],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '#VRML ',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "model/obj": const RegistryEntry(
    mediaType: 'model/obj',
    genericIcon: GenericIcon.imageXGeneric,
    comments: ['OBJ 3D model'],
    subclassOf: ['text/plain'],
    alias: [],
    globs: [Glob(pattern: '*.obj', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0:64',
            value: ' OBJ File: \'',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0:256',
            value: 'mtllib ',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "model/mtl": const RegistryEntry(
    mediaType: 'model/mtl',
    genericIcon: GenericIcon.imageXGeneric,
    comments: ['OBJ 3D model material library'],
    subclassOf: ['text/plain'],
    alias: [],
    globs: [Glob(pattern: '*.mtl', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: '# Blender MTL File: \'',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0:256',
            value: 'newmtl ',
            mask: null,
          ),
        ],
      ),
    ],
  ),
  "model/3mf": const RegistryEntry(
    mediaType: 'model/3mf',
    genericIcon: GenericIcon.imageXGeneric,
    comments: ['3MF document'],
    acronym: '3MF',
    expandedAcronym: '3D Manufacturing Format',
    subclassOf: ['application/zip'],
    alias: ['application/vnd.ms-3mfdocument'],
    globs: [Glob(pattern: '*.3mf', weight: 50, caseSensitive: false)],
  ),
  "model/stl": const RegistryEntry(
    mediaType: 'model/stl',
    genericIcon: GenericIcon.imageXGeneric,
    comments: ['STL 3D model'],
    acronym: 'STL',
    expandedAcronym: 'StereoLithography',
    subclassOf: [],
    alias: ['model/x.stl-ascii', 'model/x.stl-binary'],
    globs: [Glob(pattern: '*.stl', weight: 50, caseSensitive: false)],
    magic: [
      Magic(
        priority: 50,
        matches: [
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'solid',
            mask: null,
          ),
          Match(
            type: MatchType.string,
            offset: '0',
            value: 'SOLID',
            mask: null,
          ),
        ],
      ),
    ],
  ),
};
