// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';

/// Key derivation utilities used by the encryption bootstrap.
///
/// ## Passphrase path (Argon2id → KEK)
///
/// The passphrase is run through Argon2id to produce a 256-bit Key Encryption
/// Key (KEK). The KEK is used to AES-256-GCM-wrap the DEK. Parameters follow
/// the proposal (§4) and OWASP 2023 recommendations:
/// - Memory: 64 MiB (m = 65 536 KiB)
/// - Iterations: 3 (t = 3)
/// - Parallelism: 1 (p = 1)
/// - Output: 32 bytes (256 bits)
///
/// A fresh 256-bit random salt is generated at provisioning time and stored
/// alongside the wrapped DEK in `enc:blob`.
///
/// ## Recovery-code path (HKDF-SHA256 → recovery-KEK)
///
/// A 128-bit random recovery entropy is generated at provisioning time. The
/// 16-word BIP-39-style mnemonic shown to the user encodes this entropy. On
/// recovery, the entropy is extracted from the mnemonic and fed to
/// HKDF-SHA256 to produce the recovery-KEK, which is used to unwrap the DEK.
///
/// Using HKDF here (rather than Argon2id) is intentional: the recovery entropy
/// already has 128 bits of entropy, so password-hashing is unnecessary. The
/// HKDF info string `b'kmdb-recovery-kek-v1'` domain-separates this output from
/// any other HKDF use.
final class KeyDerivation {
  KeyDerivation._();

  // ── Argon2id parameters ────────────────────────────────────────────────────

  /// Memory cost: 64 MiB (in KiB, as Argon2 expects).
  static const int kMemoryKib = 65536;

  /// Iteration count (time cost).
  static const int kIterations = 3;

  /// Parallelism (lane count).
  static const int kParallelism = 1;

  /// Output length in bytes (256-bit KEK).
  static const int kKekLength = 32;

  // ── HKDF info strings ─────────────────────────────────────────────────────

  /// Domain-separation string for recovery-KEK derivation.
  static const List<int> kRecoveryKekInfo = [
    // b'kmdb-recovery-kek-v1'
    0x6b, 0x6d, 0x64, 0x62, 0x2d, 0x72, 0x65, 0x63,
    0x6f, 0x76, 0x65, 0x72, 0x79, 0x2d, 0x6b, 0x65,
    0x6b, 0x2d, 0x76, 0x31,
  ];

  // ── Argon2id (passphrase → KEK) ────────────────────────────────────────────

  /// Derives a 256-bit KEK from [passphrase] and [salt] using Argon2id.
  ///
  /// [salt] must be at least 16 bytes; callers should use a 32-byte random
  /// salt generated by [generateSalt].
  ///
  /// This is a compute-intensive operation (by design). On a modern device it
  /// takes 200–800 ms. Do not call from a UI thread without off-loading to an
  /// isolate.
  static Future<Uint8List> deriveKekFromPassphrase(
    String passphrase,
    Uint8List salt,
  ) async {
    final algorithm = Argon2id(
      memory: kMemoryKib,
      iterations: kIterations,
      parallelism: kParallelism,
      hashLength: kKekLength,
    );
    final key = await algorithm.deriveKey(
      secretKey: SecretKey(passphrase.codeUnits),
      nonce: salt,
    );
    return Uint8List.fromList(await key.extractBytes());
  }

  // ── HKDF-SHA256 (recovery entropy → recovery-KEK) ─────────────────────────

  /// Derives a 256-bit recovery-KEK from 128-bit [recoveryEntropy] using
  /// HKDF-SHA256.
  ///
  /// The HKDF info string `kRecoveryKekInfo` ensures this output cannot be
  /// confused with any other HKDF derivation in KMDB.
  static Future<Uint8List> deriveKekFromRecoveryEntropy(
    Uint8List recoveryEntropy,
  ) async {
    final algorithm = Hkdf(hmac: Hmac(Sha256()), outputLength: kKekLength);
    final key = await algorithm.deriveKey(
      secretKey: SecretKey(recoveryEntropy),
      nonce: <int>[],
      info: kRecoveryKekInfo,
    );
    return Uint8List.fromList(await key.extractBytes());
  }

  // ── AES-256-GCM DEK wrapping ───────────────────────────────────────────────

  /// The nonce length for DEK wrapping operations.
  static const int kWrapNonceLength = 12;

  /// The AES-GCM algorithm used for wrapping the DEK.
  static final _wrapAlgorithm = AesGcm.with256bits(
    nonceLength: kWrapNonceLength,
  );

  /// Wraps [dek] under [kek] using AES-256-GCM and returns the ciphertext.
  ///
  /// Returns `[nonce (12B)][ciphertext (32B)][tag (16B)]` — 60 bytes total.
  /// The nonce is randomly generated; callers do not need to supply one.
  static Future<Uint8List> wrapDek(Uint8List dek, Uint8List kek) async {
    final secretKey = SecretKey(kek);
    final nonce = _wrapAlgorithm.newNonce();
    final box = await _wrapAlgorithm.encrypt(
      dek,
      secretKey: secretKey,
      nonce: nonce,
    );

    final result = Uint8List(
      nonce.length + box.cipherText.length + box.mac.bytes.length,
    );
    var offset = 0;
    result.setAll(offset, nonce);
    offset += nonce.length;
    result.setAll(offset, box.cipherText);
    offset += box.cipherText.length;
    result.setAll(offset, box.mac.bytes);
    return result;
  }

  /// Unwraps a [wrappedDek] produced by [wrapDek] using [kek].
  ///
  /// Returns the 32-byte DEK.
  ///
  /// Returns `null` if the GCM tag does not match — caller should raise
  /// [EncryptionError.badCredentials].
  static Future<Uint8List?> unwrapDek(
    Uint8List wrappedDek,
    Uint8List kek,
  ) async {
    // Expected size: 12 (nonce) + 32 (DEK ciphertext) + 16 (tag) = 60 bytes.
    if (wrappedDek.length < 28) return null;

    const int nonceLen = kWrapNonceLength;
    final tagLen = 16;
    final nonce = wrappedDek.sublist(0, nonceLen);
    final tagStart = wrappedDek.length - tagLen;
    final encDek = wrappedDek.sublist(nonceLen, tagStart);
    final tag = wrappedDek.sublist(tagStart);

    final secretKey = SecretKey(kek);
    final box = SecretBox(encDek, nonce: nonce, mac: Mac(tag));

    try {
      final plaintext = await _wrapAlgorithm.decrypt(box, secretKey: secretKey);
      return Uint8List.fromList(plaintext);
    } on SecretBoxAuthenticationError {
      // Tag mismatch — wrong KEK (wrong passphrase or recovery entropy).
      return null;
    }
  }

  // ── Random generation helpers ──────────────────────────────────────────────

  /// Generates [length] cryptographically-random bytes.
  static Future<Uint8List> generateRandom(int length) async {
    // Generate cryptographically random bytes by extracting from AES keys.
    // For lengths > 32, we generate multiple keys and concatenate.
    final chunks = <int>[];
    while (chunks.length < length) {
      final k = await AesGcm.with256bits().newSecretKey();
      chunks.addAll(await k.extractBytes());
    }
    return Uint8List.fromList(chunks.sublist(0, length));
  }

  /// Generates a 32-byte (256-bit) random Argon2id salt.
  static Future<Uint8List> generateSalt() => generateRandom(32);

  /// Generates a 32-byte (256-bit) random DEK.
  static Future<Uint8List> generateDek() => generateRandom(32);

  /// Generates 16 bytes (128-bit) of random recovery entropy.
  static Future<Uint8List> generateRecoveryEntropy() => generateRandom(16);
}
