FROM kmdb-builder-base

ENV HOME_DIR="/home/builder"

RUN mkdir -p $HOME_DIR

#RUN mkdir -p $HOME_DIR/kmdb

COPY --from=PROJECT_DIR ./ $HOME_DIR/kmdb
COPY --from=KMESH_PACKAGES_DIR registry_freedesktop_mimeinfo $HOME_DIR/kmdb/packages/registry_freedesktop_mimeinfo
COPY --from=KMESH_PACKAGES_DIR core $HOME_DIR/kmdb/packages/core
COPY --from=KMESH_PACKAGES_DIR dev_loader $HOME_DIR/kmdb/packages/dev_loader
COPY --from=KMESH_PACKAGES_DIR registry_unicodedata $HOME_DIR/kmdb/packages/registry_unicodedata
COPY --from=KMESH_PACKAGES_DIR strings $HOME_DIR/kmdb/packages/strings

WORKDIR $HOME_DIR/kmdb

RUN dart pub global activate melos \
    && dart pub global activate coverage

RUN dart --disable-analytics

ENV PATH="/root/go/bin:$PATH"

ENTRYPOINT [ "make" ]
