FROM docker.io/dart:stable

RUN apt update \
    && apt install -y make pandoc \
    clang curl git unzip xz-utils zip libglu1-mesa

RUN apt install -y golang-go python3 python3-pip python3-venv

RUN apt install -y texlive fonts-dejavu-core fonts-dejavu-extra

RUN apt clean \
    && rm -rf /var/lib/apt/lists/*

RUN go install github.com/google/addlicense@latest
