// Copyright 2026 The Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// The type of action that a [UserAgent] can issue to a [Device].
enum ActionType {
  /// Initialise a new [KmdbDatabase] on the target device.
  createDb,

  /// Create a named collection on an initialised device.
  createCollection,

  /// Write a generated document to a key from the configured key pool.
  put,

  /// Read a document by key.
  get,

  /// Delete a document by key.
  delete,

  /// Trigger push/pull with the remote sync adapter.
  sync,

  /// Inject or restore a connectivity failure on the target device.
  networkPartition,

  /// Sentinel type used when an action cannot be applied in the current
  /// device FSM state. No-op actions are forwarded to the
  /// [ReconciliationAgent] with this type so that false failures are avoided.
  noOp,
}

/// A single action directed at a specific device.
///
/// Actions are generated by the [UserAgent] and executed by the [Device].
/// After execution the [Device] emits an [ActionResult] to the
/// [ReconciliationAgent].
final class Action {
  /// Creates an [Action].
  const Action({
    required this.id,
    required this.deviceId,
    required this.type,
    this.key,
    this.collectionName,
    this.document,
    this.partitioned,
  });

  /// Unique sequential identifier for this action within the run.
  final int id;

  /// The device index this action targets.
  final int deviceId;

  /// The type of action to perform.
  final ActionType type;

  /// The document key for [ActionType.put], [ActionType.get], and
  /// [ActionType.delete] actions. `null` for other action types.
  final String? key;

  /// The collection name for [ActionType.createCollection], [ActionType.put],
  /// [ActionType.get], and [ActionType.delete] actions. `null` for others.
  final String? collectionName;

  /// The document payload for [ActionType.put] actions.
  final Map<String, dynamic>? document;

  /// Whether the partition should be active (`true`) or restored (`false`).
  /// Only meaningful for [ActionType.networkPartition] actions.
  final bool? partitioned;
}

/// The result of executing an [Action] on a [Device].
final class ActionResult {
  /// Creates an [ActionResult].
  const ActionResult({
    required this.actionId,
    required this.deviceId,
    required this.type,
    required this.isNoOp,
    this.key,
    this.collectionName,
    this.document,
    this.error,
    this.hlcEncoded,
    this.syncCompleted,
    this.sstablesTransferred,
    this.syncDirection,
  });

  /// The ID of the originating [Action].
  final int actionId;

  /// The device that executed this action.
  final int deviceId;

  /// The resolved action type (may be [ActionType.noOp] if the action was
  /// inapplicable in the current device FSM state).
  final ActionType type;

  /// `true` when the action was recorded as a no-op and the expected-state
  /// model was not advanced.
  final bool isNoOp;

  /// The document key affected, for put/get/delete results.
  final String? key;

  /// The collection name, for put/get/delete/createCollection results.
  final String? collectionName;

  /// The document written or read, for put/get results.
  final Map<String, dynamic>? document;

  /// The error message if the action failed, `null` on success.
  final String? error;

  /// The HLC timestamp (encoded as a 64-bit int) of the write, for put/delete
  /// results. Populated by [ReconciliationAgent] from the stored document's
  /// `_hlc` system field when available.
  final int? hlcEncoded;

  /// Whether a sync operation completed successfully. Only meaningful for
  /// [ActionType.sync] results.
  final bool? syncCompleted;

  /// Number of SSTables transferred during a sync. Only meaningful for
  /// [ActionType.sync] results.
  final int? sstablesTransferred;

  /// Direction of the sync: `'push'`, `'pull'`, or `'both'`. Only meaningful
  /// for [ActionType.sync] results.
  final String? syncDirection;
}
